update chapter library
ostis-ai/monography2022 pull request #121
Opened 2023-02-25 20:29 UTC by MksmOrlov

2023-03-03 15:09 UTC, SHtress approved these changes

2023-03-03 15:09 UTC, SHtress commented on author/part5/chapter_library.tex
> +Повторное использование готовых компонентов широко применяется во многих отраслях, связанных с разработкой различного рода систем, поскольку позволяет уменьшить трудоемкость разработки и ее стоимость
Два раза "разработка" режет слух, возможно второй раз ее можно опустить оставив просто трудоемкость.
"создаваемых компьютерных систем", до этого говорилось просто про системы, возможно, лучше либо убрать здесь компьютерных, либо добавить выше

2023-03-03 21:01 UTC, MksmOrlov commented on author/part5.tex
> +		сопровождения.}
Критикуешь -- предлагай :)

2023-03-03 21:03 UTC, MksmOrlov commented on author/part5.tex
> +		приспособленными, что требует разработки принципиально новых компьютеров.}
Согласен, спасибо. В целом начинать предложение с союза не очень была идея

2023-03-03 21:04 UTC, MksmOrlov commented on author/part5.tex
> +Для решения возникших недостатков предлагаются следующие принципы (см. \scncite{Golenkov2011} и \scncite{Zalivako2011}):
Согласен, спасибо

2023-03-03 21:05 UTC, MksmOrlov commented on author/part5.tex
> +Для решения возникших недостатков предлагаются следующие принципы (см. \scncite{Golenkov2011} и \scncite{Zalivako2011}):
Здорово, спасибо

2023-03-04 11:35 UTC, SHtress commented on author/part5.tex
> +	\item{Отсутствуют подходы, позволяющие на некоторой универсальной основе интегрировать научные и практические результаты в области искусственного интеллекта, что порождает высокую степень дублирован
Аналогично по стилистике здесь тоже возможно стоит подправить
```suggestion
	\item{Высокая степень дублирования результатов. Отсутствуют подходы, позволяющие на некоторой универсальной основе интегрировать научные и практические результаты в области искусственного интеллекта, что порождает множество неунифицированных форматов представления данных.}
```

2023-03-04 11:36 UTC, SHtress commented on author/part5.tex
> +		сопровождения.}
Длительные сроки разработки и высокая трудоемкость (высокий уровень трудоемкости) их сопровождения?

2023-03-05 17:04 UTC, MksmOrlov commented on author/part5.tex
> +		сопровождения.}
В последнем коммите (2013) испрваил

2023-03-05 17:04 UTC, MksmOrlov commented on author/part5.tex
> +	\item{Отсутствуют подходы, позволяющие на некоторой универсальной основе интегрировать научные и практические результаты в области искусственного интеллекта, что порождает высокую степень дублирован
В последнем коммите (2013) исправил

2023-03-05 17:48 UTC, ShunkevichDV requested changes

2023-03-05 17:48 UTC, ShunkevichDV commented on author/part3/chapter_actions.tex
> +	\item в дальнейшем это позволит интеллектуальной системе самостоятельно обращаться в библиотеку компонентов решателей задач (смотрите \ref{ps_components_section}~\nameref{ps_components_section}) и п
В таких случаях пишем все же (см. <..>)

2023-03-05 17:48 UTC, ShunkevichDV commented on author/part5/chapter_library.tex
> +\chapauthortoc{Орлов М.К.\\Шункевич Д.В.}
Такое надо согласовать с Владимиром Васильевичем, некоторые фамилии здесь были ради привязки к диссертациям больше. Мы все друг другу помогаем рано или поздно

2023-03-05 17:48 UTC, ShunkevichDV commented on author/part5/chapter_library.tex
> +	\item{контейнер -- хранение набора объектов в памяти;}
Мы наоборот везде пишем \item без {}

2023-03-05 17:48 UTC, ShunkevichDV commented on author/part5/chapter_library.tex
> +% Здесь аккуратно упоминается понятие компонента, пока что оно интуитивно понимается читателем, позже описывается подробнее, норм? Сначала ведь был компонент, потом библиотека, но мы идём от задачи,
Если это тревожит, можно явно сослаться на параграф или пункт, где подробнее описаны компоненты и их типология

2023-03-05 18:15 UTC, MksmOrlov commented on author/part5/chapter_library.tex
> +% Здесь аккуратно упоминается понятие компонента, пока что оно интуитивно понимается читателем, позже описывается подробнее, норм? Сначала ведь был компонент, потом библиотека, но мы идём от задачи,
Сделал

2023-03-05 19:00 UTC, ShunkevichDV approved these changes
Поправить точки

2023-03-05 19:00 UTC, ShunkevichDV commented on biblio.bib
> +	shorthand    = {Шункевич.Д.В.Модели СКПМОЗнОСС-2013ст},
В shorthand точка после фамилии не надо, см. правила в начале раздела библиографии

2023-03-05 19:07 UTC, MksmOrlov commented on biblio.bib
> +	shorthand    = {Шункевич.Д.В.Модели СКПМОЗнОСС-2013ст},
У нас в половине библиографии стоит точка, вот я и скопипистил.

2023-03-05 19:21 UTC, merged