Chapter 6.3. Search subsystem description
ostis-ai/monography2022 pull request #149
Opened 2023-03-13 08:47 UTC by NikitaZotov

2023-03-24 18:41 UTC, ShunkevichDV requested changes

2023-03-24 18:41 UTC, ShunkevichDV commented on author/part6/chapter_soft_platform.tex
> +\textit{Синтаксис SCin-кода} задается: (1) \textit{Алфавитом SCin-кода}, (2) отношением инцидентности \textit{sc-адрес элемента sc-памяти*}. Важно отметить, что \textit{Синтаксис SCin-кода}, как и си
Может быть имеет смысл что-то сказать о семантике, например, что семантика SCin-кода задается вот этим отношением как раз

2023-03-24 18:41 UTC, ShunkevichDV commented on author/part6/chapter_soft_platform.tex
> +	\item \textit{Синтаксические и семантические классы элементов sc-памяти} могут комбинироваться между собой для получения более частных классов. С точки зрения программной реализации такая комбинация
А почему Битовое сложение с большой, обычное сложение же с маленькой. Это имя отношения, то есть класса связок

2023-03-24 18:41 UTC, ShunkevichDV commented on author/part6/chapter_soft_platform.tex
> +	\item Важно отметить, что каждому из выделенных классов элементов (кроме классов, получаемых путем комбинации других классов) однозначно соответствует порядковый номер бита в линейной памяти, что мо
```suggestion
	\item Важно отметить, что каждому из выделенных классов элементов (кроме классов, получаемых путем комбинации других классов) однозначно соответствует порядковый номер бита в линейной памяти, что можно заметить, глядя на соответствующие числовые выражения этих классов. Это означает, что классы элементов не включаются друг в друга (хоть в спецификации это и не так), например, указание принадлежности к классу \textit{элементов sc-памяти, соответствующих sc-дуге позитивной принадлежности} не означает автоматическое указание принадлежности \textit{элементов sc-памяти, соответствующих sc-дуге принадлежности}. На уровне реализации это позволяет сделать операции комбинирования и сравнения меток более эффективными.
```

2023-03-24 18:41 UTC, ShunkevichDV commented on author/part6/chapter_soft_platform.tex
> +Логически текущий \textit{Программный интерфейс Реализации sc-памяти в ostis-платформе} разделяется на два программных интерфейса: \textit{Программный интерфейс информационно-формирующих методов Реал
```suggestion
Логически текущий \textit{Программный интерфейс Реализации sc-памяти в ostis-платформе} разделяется на два программных интерфейса: \textit{Программный интерфейс информационно-формирующих методов Реализации sc-памяти в ostis-платформе} и \textit{Программный интерфейс информационно-поисковых методов Реализации sc-памяти в ostis-платформе}. В первую очередь, такое разделение связано с тем, что реализация методов информационного поиска в текущей \textit{Реализации sc-памяти в ostis-платформе} достаточно сложна и требует намного большего уточнения при описании этой реализации. Также это разделение программного интерфейса позволяет выделять и структурировать спецификацию методов \textit{Программного интерфейса Реализации sc-памяти в ostis-платформе} таким образом, чтобы она оставалась однообразной, компактной и простой для внешнего пользователя. Как такового физического разделения в \textit{Программном интерфейсе Реализации sc-памяти в ostis-платформе} не существует, все методы \textit{Программного интерфейса Реализации sc-памяти в ostis-платформе} могут быть использованы одним и тем же программным образом и являются компонентами \textit{Библиотеки многократно используемых компонентов Программного варианта реализации ostis-платформы}, то есть могут быть использованы при реализации других компонентов специального назначения.
```

2023-03-24 18:41 UTC, ShunkevichDV commented on author/part6/chapter_soft_platform.tex
> +\scnheader{Метод создания элемента в sc-памяти с заданным классом, соответствующего некоторому sc-узлу}
Может быть Метод создания элемента в sc-памяти, соответствующего некоторому sc-узлу заданного класса?

Ну и дальше так же для коннектора

2023-03-24 18:41 UTC, ShunkevichDV commented on author/part6/chapter_soft_platform.tex
> +	\scnitem{Метод создания программного механизма поиска трёхэлементных конструкций в sc-памяти}
Я понимаю, что старался обобщить как-то, но "создание программного механизма" звучит очень уж вычурно. Мы ведь выше ввели уже наверное понятие итератора, может быть его использовать? Создание итератора звучит попроще, ну или хотя бы создание структуры или шаблона

2023-03-24 18:41 UTC, ShunkevichDV commented on author/part6/chapter_soft_platform.tex
> +Для \textit{Метода создания программного механизма поиска трёхэлементных конструкций в sc-памяти}, как и для \textit{Метода создания программного механизма поиска пятиэлементных конструкций в sc-памя
Можно явно сослаться на роли в SCP для лучшего понимания смысла f и а

2023-03-24 18:41 UTC, ShunkevichDV commented on author/part6/chapter_soft_platform.tex
> +		\scnsuperset{локальный идентификатор не привязан раннее к sc-адресу элементу программного объекта трёхэлементной конструкции в заданном программном объекте графа-образца}
```suggestion
		\scnsuperset{локальный идентификатор не привязан раннее к sc-адресу элемента программного объекта трёхэлементной конструкции в заданном программном объекте графа-образца}
```

2023-03-24 18:41 UTC, ShunkevichDV commented on author/part6/chapter_soft_platform.tex
> +Данная \textit{Реализация подсистемы взаимодействия c sc-памятью на основе языка JSON} позволяет ostis-системам взаимодействовать с системами из внешней среды на основе общепринятого транспортного фо
Выше кажется использовался другой термин, а не  Программная платформа ostis-систем

2023-03-24 18:41 UTC, ShunkevichDV commented on author/part6/chapter_soft_platform.tex
> +    \item Поскольку в основе ostis-систем лежит идея агентно-ориентированной обработки знаний (асинхронной обработки), а память таких систем должна быть одновременно распределённой и общей, то необхо
```suggestion
    \item Поскольку в основе ostis-систем лежит идея агентно-ориентированной обработки знаний (асинхронной обработки), а память таких систем должна быть одновременно распределённой и общей, то необходимо, чтобы каждая из них (в частности, самостоятельная ostis-система) могла общаться с другими ostis-системами. Причём такое общение может и должно происходить посредством инициирования событий в памяти этих систем. Отсюда следует однозначный вывод, что протокол HTTP не может быть использован в передовых интеллектуальных системах нового поколения по причине однонаправленности создаваемого им соединения.
```

2023-03-24 21:46 UTC, NikitaZotov commented on author/part6/chapter_soft_platform.tex
> +	\scnitem{программный объект трёхэлементной конструкции}
Пока будет _программный объект трёхэлементной конструкции заданного графа-образца_. Обсужу с ВВ

2023-03-24 21:46 UTC, NikitaZotov commented on author/part6/chapter_soft_platform.tex
> +\scnheader{Метод доступа к sc-адресу элемента заданной конструкции в sc-памяти по номеру позиции этого элемента в заданной конструкции}
обсудили. Нужно поговорить с ВВ

2023-03-25 15:23 UTC, MksmOrlov requested changes
В прогрессе. Пока что остановился на Пункт 6.3.4.2.
[Программная платформа ostis-систем (2) (1).pdf](https://github.com/ostis-ai/monography2022/files/11069250/ostis-.2.1.pdf)

2023-03-26 11:15 UTC, ShunkevichDV approved these changes

2023-03-26 15:24 UTC, MksmOrlov commented on author/part6/chapter_soft_platform.tex
> +До настоящего времени существует обширное множество различных решений в области автоматизации проектирования и разработки \textit{программных компьютерных систем} (см. \scncite{Iliadis2019}), позволя
\textit{программных компьютерных систем}

2023-03-26 15:24 UTC, MksmOrlov commented on author/part6/chapter_soft_platform.tex
> +	\scniselement{C}
лишнее же

2023-03-27 12:01 UTC, merged