Add Davydenko materials, add KBE info, add builder info
ostis-ai/monography2022 pull request #155
Opened 2023-03-15 13:24 UTC by SHtress

2023-03-16 20:00 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +Lанный факт приводит к многократной повторной разработке содержательно одних и тех же компонентов для разных баз знаний.
```suggestion
Данный факт приводит к многократной повторной разработке содержательно одних и тех же компонентов для разных баз знаний.
```

2023-03-16 20:13 UTC, NikitaZotov requested changes

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +пользуемых компонентов баз знаний;
```suggestion
\item установка Ядра sc-моделей баз знаний из библиотеки многократно используемых компонентов баз знаний;
```

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\item установка Ядра машин обработки баз знаний из библиотеки многократно используемых компонентов машин обработки баз знаний, т. е. набора базовых многократно используемых компонентов машин обработк
```suggestion
\item установка Ядра машин обработки баз знаний из библиотеки многократно используемых компонентов машин обработки баз знаний, то есть набора базовых многократно используемых компонентов машин обработки баз знаний, необходимых для работы стартовой версии ostis-системы;
```

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\item установка Ядра машин обработки баз знаний из библиотеки многократно используемых компонентов машин обработки баз знаний, т. е. набора базовых многократно используемых компонентов машин обработк
нужно везде поправить

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\scnheader{Реализация вспомогательных инструментальных средств для работы с sc-памятью}
```suggestion
\scnheader{Реализация транслятора исходных текстов базы знаний в sc-память ostis-платформы}
```

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\scnrelfrom{компонент программной системы}{Реализация сборщика базы знаний из исходных текстов, записанных в SCs-коде}
```suggestion
\scniselement{многократно используемый компонент ostis-систем, хранящийся в виде файлов исходных текстов}
\scniselement{атомарный многократно используемый компонент ostis-систем}
\scniselement{зависимый многократно используемый компонент ostis-систем}
```

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\begin{scnindent}
```suggestion
```

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\end{scnindent}
```suggestion
```

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +     \scntext{пояснение}{Сборщик базы знаний из исходных текстов позволяет осущ ествить сборку базы знаний из набора исходных текстов, записанных в SCs-коде с ограничениями  в бинарный формат, воспри
```suggestion
     \scntext{пояснение}{\textit{Реализация транслятора исходных текстов базы знаний в sc-память ostis-платформы} позволяет осуществить сборку базы знаний из набора исходных текстов, записанных в SCs-коде с ограничениями  в бинарный формат, воспринимаемый \textit{Программной моделью sc-памяти}. При этом возможна как сборка \scnqq{с нуля} (с уничтожением ранее созданного слепка памяти), так и аддитивная сборка, когда информация, содержащаяся в заданном множестве файлов, добавляется к уже имеющемуся слепку состояния памяти.
```

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +     \scntext{пояснение}{Сборщик базы знаний из исходных текстов позволяет осущ ествить сборку базы знаний из набора исходных текстов, записанных в SCs-коде с ограничениями  в бинарный формат, воспри
```suggestion
     \scntext{пояснение}{Сборщик базы знаний из исходных текстов позволяет осуществить сборку базы знаний из набора исходных текстов, записанных в SCs-коде с ограничениями в бинарный формат, воспринимаемый \textit{Программной моделью sc-памяти}. При этом возможна как сборка \scnqq{с нуля} (с уничтожением ранее созданного слепка памяти), так и аддитивная сборка, когда информация, содержащаяся в заданном множестве файлов, добавляется к уже имеющемуся слепку состояния памяти.
```

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\begin{scnindent}
```suggestion
\begin{scnrelfromset}{зависимости компонента}
	\scnitem{Реализация sc-памяти в ostis-платформе}
	\scnitem{Библиотека методов и структур данных C++ Standart Library}
\end{scnrelfromset}
```

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +Полученный исходные файлы в дальнейшем могут быть погружены в базу знаний ostis-системы с помощью специального sc-builder, который является частью реализации машины обработки знаний.
Здесь не так как есть написано. Следует описать транслятор из scg в scs

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +В рамках главного окна имеется панель инструментов, и меню приложения.
Было бы классно если бы сама Реализация KBE была описана в виде спецификации на SCn и его компоненты тоже

2023-03-16 20:13 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +Для создания исходных файлов на языке SCg предлагается использовать KBE (Knowledg Base source Editor).
Лучше не использовать сокращение KBE. Следует ввести полную русскоязычную расшифровку

2023-03-17 03:08 UTC, SHtress commented on author/part5/chapter_kb_design.tex
> +Полученный исходные файлы в дальнейшем могут быть погружены в базу знаний ostis-системы с помощью специального sc-builder, который является частью реализации машины обработки знаний.
Нужно ли это указывать в монографии? Это нюансы реализации, зачем они пользователю?

2023-03-17 03:09 UTC, SHtress commented on author/part5/chapter_kb_design.tex
> +В рамках главного окна имеется панель инструментов, и меню приложения.
Может быть когда-нибудь так и будет, но явно не сейчас

2023-03-17 06:50 UTC, SHtress commented on author/part5/chapter_kb_design.tex
> +Для создания исходных файлов на языке SCg предлагается использовать KBE (Knowledg Base source Editor).
Если это не согласовано, то добавлено не будет

2023-03-17 08:56 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +Полученный исходные файлы в дальнейшем могут быть погружены в базу знаний ostis-системы с помощью специального sc-builder, который является частью реализации машины обработки знаний.
Если так говорить, то глава по платформе вообще не нужна

2023-03-20 23:54 UTC, KsenBantsevich commented on author/part5/chapter_kb_design.tex
> +Для создания исходных файлов на языке SCg предлагается использовать KBE (Knowledg Base source Editor).
```suggestion
Для создания исходных файлов на языке SCg предлагается использовать KBE (Knowledge Base source Editor). 
```

2023-03-23 22:58 UTC, NikitaZotov requested changes

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +База знаний является ключевым компонентом интеллектуальной системы, которая в систематизированном виде включает в себя все знания, необходимые интеллектуальной системе для ее функционирования.
Не забывай выделять курсивом (то есть через textit) понятия, которые вводятся в других главах

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +По поддержке коллективной разработки:
Может можно эти классификации сделать в SCn?

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +По поддержке коллективной разработки:
Можно в виде разбиений

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\item установка Ядра sc-моделей баз знаний из библиотеки многократно используемых компонентов баз знаний;
```suggestion
\item установка Ядра sc-модели базы знаний ostis-системы из библиотеки многократно используемых компонентов баз знаний;
```

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\item выбор и установка платформы интерпретации модели ostis-системы;
```suggestion
\item выбор и установка платформы для интерпретации sc-модели ostis-системы;
```

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\item установка Ядра машин обработки баз знаний из библиотеки многократно используемых компонентов машин обработки баз знаний, то есть набора базовых многократно используемых компонентов машин обрабо
```suggestion
\item установка Ядра машин обработки баз знаний из Библиотеки многократно используемых компонентов машин обработки баз знаний, то есть набора базовых многократно используемых компонентов машин обработки баз знаний, необходимых для работы стартовой версии ostis-системы;
```

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +\item установка Ядра sc-моделей баз знаний из библиотеки многократно используемых компонентов баз знаний;
```suggestion
\item установка Ядра sc-моделей баз знаний из Библиотеки многократно используемых компонентов баз знаний;
```

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +На панель инструментов, как и в пользовательских интерфейсах большинства приложений, вынесены наиболее часто используемые команды:
Если хочешь, можем это всё описать в виде SCn. Я помогу

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +Полученный исходные файлы в дальнейшем могут быть погружены в базу знаний ostis-системы с помощью специального sc-builder, который является частью реализации машины обработки знаний.
```suggestion
Полученный исходные файлы в дальнейшем могут быть погружены в базу знаний ostis-системы с помощью Реализации транслятора исходных текстов базы знаний в sc-память ostis-платформы.
```

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +Так же имеется встроенный редактор в sc-web, обладающий схожим с KBE функционалом, но при этом позволяющий редактировать базу знаний в режиме реального времени и без создания исходных файлов.
```suggestion
Так же имеется редактор текстов базы знаний, являющийся частью \textit{Реализации интерпретатора sc-моделей пользовательских интерфейсов ostis-систем в Программном варианте реализации ostis-платформы}, обладающий схожим с KBE функционалом, но при этом позволяющий редактировать базу знаний в режиме реального времени и без создания исходных файлов.
```

2023-03-23 22:58 UTC, NikitaZotov commented on author/part5/chapter_kb_design.tex
> +Полученный исходные файлы в дальнейшем могут быть погружены в базу знаний ostis-системы с помощью специального sc-builder, который является частью реализации машины обработки знаний.
в textit тоже оберни

2023-03-24 19:26 UTC, ShunkevichDV requested changes

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Таким образом, актуальной является задача разработки модели баз знаний, которая, с одной стороны, обеспечит общий унифицированный формальный фундамент для представления различных видов знаний в рамка
Согласен, как минимум не стоит это делить на такое количество абзацев. Можно объединить в 2-3 абзаца по смыслу

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +
Первую часть текста опять же не стоит делить на такое количество абзацев, можно часть объединить
Во второй части надо добавить ссылки как минимум на работы автора текста

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Коллективный же процесс включает в себя средства и методы для автоматического или полуавтоматического согласования общей базы знаний с индивидуальными базами знаний пользователей. То есть он включает
```suggestion
Коллективный же аспект включает в себя средства и методы для автоматического или полуавтоматического согласования общей базы знаний с индивидуальными базами знаний пользователей. То есть он включает в себя процессы создания предложений по изменению базы знаний, их рассмотрение и внесение в общую базу знаний.
```

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Так как в основе любой базы знаний лежат онтологии, то методы и средства разработки онтологий являются важнейшей частью технологий разработки баз знаний.
```suggestion
Так как в основе любой современной базы знаний лежат онтологии, то методы и средства разработки онтологий являются важнейшей частью технологий разработки баз знаний.
```

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +\scnheader{Методология разработки онтологий}
```suggestion
\scnheader{методология разработки онтологий}
```

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +		\scnitem{методологии, поддерживающие совместную коллективную разработку онтологии}
в названиях классов везде именительный падеж

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +		\scnitem{методологии предусматривающие способы формализации}
нужна запятая после слова методология, здесь и в других местах проверить

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +\item установка Ядра машин обработки баз знаний из Библиотеки многократно используемых компонентов машин обработки баз знаний, то есть набора базовых многократно используемых компонентов машин обрабо
```suggestion
\item установка Ядра решателей задач из Библиотеки многократно используемых компонентов решателей задач, то есть набора базовых многократно используемых компонентов решателей задач, необходимых для работы стартовой версии ostis-системы;
```

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Текущая реализация платформы и машины обработки знаний поддерживает работу с исходными файлам базы знаний.
Дальше везде нужно заменить на "файл исходного текста", термин "исходный файл" мне кажется несет другой смысл

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Для создания таких исходных файлов на языке SCs можно воспользоваться любым текстовы редактором.
Термины по стандарту - SCs-код, SCg-код, нужно везде проверить
В свою очередь sc.g-узел, sc.g-шина и т.д., с маленькой буквы

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Для создания исходных файлов на языке SCg предлагается использовать KBE (Knowledge Base source Editor).
Ссылку на репо надо

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +\item Режим создания SCg-пар (дуг).
В соответствующем разделе есть sc.g-дуги только, про пары лучше не говорить

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Полученный исходные файлы в дальнейшем могут быть погружены в базу знаний ostis-системы с помощью \textit{Реализации транслятора исходных текстов базы знаний в sc-память ostis-платформы}.
Добавить ссылку на параграф, где это описывается

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +\item выбор и установка платформы для интерпретации sc-модели ostis-системы;
Везде по главе надо проверить, согласованный термин - ostis-платформа

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +\item установка Ядра машин обработки баз знаний из Библиотеки многократно используемых компонентов машин обработки баз знаний, то есть набора базовых многократно используемых компонентов машин обрабо
Везде по главе надо проверить, согласованный термин - решатель задач

2023-03-24 19:26 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +При необходимости разработки объемной базы знаний может вводиться иерархия разработчиков, соответствующая иерархии разделов разрабатываемой базы знаний.
Было бы неплохо из той же диссертации перенести хотя бы описания ролей, вот презентация, в которой это есть в сжатом виде. Может что еще полезное в ней найдется
[СПБЗ.pptx](https://github.com/ostis-ai/monography2022/files/11065948/default.pptx)

2023-03-25 10:57 UTC, SHtress commented on author/part5/chapter_kb_design.tex
> +Полученный исходные файлы в дальнейшем могут быть погружены в базу знаний ostis-системы с помощью \textit{Реализации транслятора исходных текстов базы знаний в sc-память ostis-платформы}.
Добавил, на тот ли - не уверен.

2023-03-26 11:18 UTC, ShunkevichDV approved these changes
Исправить техническое замечание

2023-03-26 11:18 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +	\scnitem{контроль целостности и непротиворечивости всей базы знаний}
здесь и далее в таких местах надо scnfileitem, потому что функции сформулированы на естественном языке, это же не идентификаторы понятий конкретных

2023-03-26 17:35 UTC, ShunkevichDV approved these changes
Мелкая опечатка

2023-03-26 17:35 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Для обеспечения свойства рефлексивности интеллектуальной системы, в частности, возможности автоматизации анализа истории эволюции базы знаний и генерации планов по ее развитию, вся деятельность, связ
```suggestion
Для обеспечения свойства рефлексивности интеллектуальной системы, в частности, возможности автоматизации анализа истории эволюции базы знаний и генерации планов по ее развитию, вся деятельность, связанная с разработкой базы знаний, должна специфицироваться в самой этой базе знаний теми же средствами, что и предметная часть (см. \scncite{Davydenko2018}).
```

2023-03-27 07:44 UTC, ShunkevichDV approved these changes

2023-03-29 13:56 UTC, merged