Chapters questions and gis
ostis-ai/monography2022 pull request #160
Opened 2023-03-17 07:05 UTC by NikitaZotov

2023-03-20 18:01 UTC, MksmOrlov requested changes

2023-03-23 15:58 UTC, MksmOrlov requested changes

2023-03-23 15:58 UTC, MksmOrlov commented on author/part3/chapter_requests.tex
> +	\scnitem{Самодумкин С.~А.}
Add Ниикта Зотов

2023-03-23 15:58 UTC, MksmOrlov commented on biblio.bib
> +	author      = {Самодумкин, СА},
неправильно инициалы оформлены

2023-03-24 20:04 UTC, ShunkevichDV requested changes

2023-03-24 20:04 UTC, ShunkevichDV commented on author/part7/chapter_gis.tex
> +		\scnitem{водные объекты и гидротехнические сооружения}
В единственном числе и как-то одинаково надо называть, например слово объект добавлять - "объект дорожной сети или дорожное сооружение"

2023-03-24 20:04 UTC, ShunkevichDV commented on author/part7/chapter_gis.tex
> +		\scnitem{точечный объект}
```suggestion
		\scnitem{точечный объект местности}
```

2023-03-24 20:04 UTC, ShunkevichDV commented on author/part7/chapter_gis.tex
> +				\scnitem{колодец}
Сейчас не очень актуально, но в будущем надо будет подумать над тем, как отделить терминологически колодец и изображение колодца на карте, ну и для остальных то же самое

2023-03-24 20:04 UTC, ShunkevichDV commented on author/part7/chapter_gis.tex
> +Из литературы можно выделить три типа онтологий:
Тут надо как-то изменить, чтобы согласовывалось с Главой про онтологии, привязать к OSTIS

2023-03-24 20:04 UTC, ShunkevichDV commented on author/part7/chapter_gis.tex
> +Функции, по выделению отношений между географическими объектами, конвертера карт в графодинамическую память должны найти все возможные отношения «пересечения», «включения», «примыкания» и «соседства
Кавычки `` '' везде
Таблица не 2.1 явно

2023-03-29 15:10 UTC, ShunkevichDV requested changes

2023-03-29 15:10 UTC, ShunkevichDV commented on author/part3/chapter_requests.tex
Нужны 
1. Какие-то хоть пару предложений в качестве вывода к главе, а еще лучше заключение, в котором сказать, что например все перечисленные агенты надо реализовывать
2. Ссылка на раздел по решателям, в частности, на параграф про действия в sc-памяти. Сказать, что формирование ответа на вопросы происходит путем выполнения действий в sc-памяти, типология который рассмотрена там вот

2023-03-29 15:10 UTC, ShunkevichDV commented on author/part7/chapter_gis.tex
> +\scntext{аннотация}{}
Не забыть

2023-03-29 15:10 UTC, ShunkevichDV commented on author/part7/chapter_gis.tex
> +\textit{интеллектуализация геоинформационных} систем предполагает решение следующих задач:
Что-то не так, я бы слова типа интеллектуализация вообще курсивом лучше не выделял, если это не например глава 1.3, где конкретно говорится о том, как ее обеспечить

2023-03-29 15:10 UTC, ShunkevichDV commented on author/part7/chapter_gis.tex
> +\subsection{Геосемантические элементы: местоположение, топология, близость, ориентация, динамика}
Пора бы добавлять, два дня осталось

2023-03-29 15:10 UTC, ShunkevichDV commented on author/part7/chapter_gis.tex
> +Наиболее часто онтологии, используемые в геоинформатике, обычно рассматриваются как доменные онтологии, которые принято называть географическими онтологиями, или геоонтологиями (F. Fonseca, Câmara, M
Пора оформлять

2023-04-03 14:55 UTC, ShunkevichDV approved these changes

2023-04-03 20:20 UTC, MksmOrlov approved these changes

2023-04-03 20:56 UTC, merged