sc_code
ostis-ai/monography2022 pull request #162
Opened 2023-03-17 21:35 UTC by shaversion

logic
computers
chapters updated

2023-03-24 00:00 UTC, NikitaZotov requested changes

2023-03-24 00:00 UTC, NikitaZotov commented on author/part6/chapter_computers.tex
> +\section{Подходы к построению ассоциативного семантического компьютера}
Ниже описаны варианты реализации семантического компьютера. Предлагаю разбить этот параграф на такие же варианты реализации и сделать их параграфами

2023-03-24 21:58 UTC, ShunkevichDV requested changes

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_logic.tex
> +	\scnnote{Иррефлексивное слотовое бинарное отношение --- бинарное отношение, любая связка которого не является связкой,обозначенной петлевой дугой (дугой с совпадающим началом и концом).}
Мне кажется здесь нужно как-то разрезать по смыслу с параграфами про традиционные логики и множествами. Чем это определение принципиально отличается от просто определения иррефлексивного бинарного отношения?

термин слотовое и неслотовое надо пояснить, нигде не сказано, что это и зачем

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_logic.tex
>  	\scnheader{отношение нестрогого порядка}
Это все есть в разделе про теорию отношений, зачем это здесь

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_logic.tex
>  Множество посылок.Отношение выводимости.
В начале параграфа нужно что-то сказать о том, что такое вообще прикладные логики, иначе просто идет пачка понятий, не понятно, зачем это все и к чему

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_sc_code.tex
> +		\scnitem{ключевой запрос’}
было все верно, зачем вы меняете это

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_sc_code.tex
> +Понятие \textbf{\textit{SC-пространства}} наряду с понятием \textbf{\textit{SC-кода}} является необходимым для уточнения и формализации понятия смысла информационных конструкций и в унификации смысло
```suggestion
Понятие \textbf{\textit{SC-пространства}} наряду с понятием \textbf{\textit{SC-кода}} является необходимым для уточнения и формализации понятия смысла информационных конструкций и в унификации смыслового представления информации. В \textbf{\textit{SC-пространстве}} можно выделять структуры, связанные как с синтаксическими свойствами текстов \textbf{\textit{SC-кода}}, так и с его семантикой. В последнем случае речь можно вести о ``смысловом пространстве''. Смысл информационной конструкции, в конечном счёте, определяется (1) внутренними связями всех элементарных фрагментов этой конструкции и (2) её внешними связями с элементами смыслового пространства (её положением в контексте). Смысловое пространство является результатом естественного становления знаний в процессе их интеграции.
```

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_sc_code.tex
> +Важнейшим достоинством \textbf{\textit{SC-пространства}} является возможность уточнения таких понятий, как понятие аналогичности (сходства и отличия) различных описываемых «внешних» сущностей, аналог
```suggestion
Важнейшим достоинством \textbf{\textit{SC-пространства}} является возможность уточнения таких понятий, как понятие аналогичности (сходства и отличия) различных описываемых "внешних"{} сущностей, аналогичности унифицированных семантических сетей (текстов \textbf{\textit{SC-кода}}), понятие семантической близости описываемых сущностей (в том числе, и текстов \textbf{\textit{SC-кода}}).
```

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_sc_code.tex
>  Следует отметить, что в силу абстрактности языков модели унифицированного семантического представления знаний и условности выбора меток элементов их текстов, нельзя исключить, что объединение двух пр
кавычки везде, где идет название термина, надо делать ``вот такими''

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_sc_code.tex
> +	\scnheader{sc-связка}
Эти все понятия введены уже в предыдущих параграфах этой же главы, зачем их тут еще раз вводить

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_sc_code.tex
> +\begin{SCn}
Нужно согласовать с синтаксисом и семантикой SC-кода, которые выше описаны

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_sc_code.tex
> +	\scnheader{sc-структура\scnrolesign}
Как это соотносится с понятием sc-структуры в терминах предыдущих параграфов?

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_sc_code.tex
>  \begin{SCn}
Такие же термины уже рассмотрены в ПрО sc-структур, нужно согласовывать смысл

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part2/chapter_sc_code.tex
> +В силу неполноты выразительных средств для представления изменяющихся со временем знаний, отсутствия определённой пространственно-временной модели, наличия семантически неопределённых или слабоопреде
Такие вещи нельзя писать в монографии очевидно

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part6/chapter_computers.tex
> +\section{Подходы к построению ассоциативного семантического компьютера}
В параграфе ничего не сказано про подходы к построению компьютера, а построена онтология существующих архитектур и выделены признаки их классификации
Я бы назвал параграф Анализ существующих архитектур вычислительных систем или Онтология архитектур вычислительных систем.

2023-03-24 21:58 UTC, ShunkevichDV commented on author/part6/chapter_computers.tex
> + Для определения архитектуры ассоциативных семантических компьютеров ostis-систем, в соответствии с выявленными классами и признаками,а также выработанными общими принципами лежащих в основе таких ар
В целом я согласен, но приводить тут этот параграф нет смысла, потому что далее такой сравнительный анализ не производится, нужно подвести какие-то итоги по результатам параграфа и увязать с тем, что дальше будет

2023-03-29 15:58 UTC, ShunkevichDV approved these changes
Можно принять как версию и править потом содержание и библиографию в других PR

2023-03-30 07:22 UTC, NikitaZotov approved these changes

2023-03-30 17:32 UTC, merged