update chapter 7.5
ostis-ai/monography2022 pull request #164
Opened 2023-03-19 16:21 UTC by grakova

2023-03-23 23:54 UTC, NikitaZotov requested changes

2023-03-23 23:54 UTC, NikitaZotov commented on author/part7/chapter_learning_systems/section_semantic_model_and_knowledge_control.tex
> +Поскольку подсистема также должна позволять вычислять подобие между любыми двумя семантическими графами в базе знаний, вычисленное подобие может быть использовано в будущем для проверки ответов польз
```suggestion
Поскольку подсистема также должна позволять вычислять подобие между любыми двумя семантическими графами в базе знаний, вычисленное подобие может быть использовано в будущем для проверки ответов пользователя на новые типы тестовых вопросов и для решения других задач, таких как слияние знаний. В базе знаний содержится большое количество семантических графов, имеющих схожую структуру с семантическими графами ответов на объективные вопросы, то есть семантических графов, описанных с помощью фактических знаний, поэтому подход, используемый для вычисления подобия между ответами на объективные вопросы, также может быть использован для вычисления подобия между семантическими графами, описанными с помощью фактических знаний. Поскольку семантический граф ответов на объективные вопросы и семантический граф, описанный с использованием фактических знаний, имеют схожую семантическую структуру, далее они будут единообразно именоваться семантическим графом ответов на объективные вопросы. Но семантические графы этого типа обычно имеют семантические графы, логически эквивалентные им, например, определение симметричной разности может быть выражено в этих двух формах:
```

2023-03-23 23:54 UTC, NikitaZotov commented on author/part7/chapter_learning_systems/section_semantic_model_and_knowledge_control.tex
> +В ostis-системах sc-конструкция, состоящая из sc-кортежа, sc-узла отношения, sc-узла ролевого отношения и sc-коннектора, используется для описания логических связок (такие как отрицание ($\lnot$) и и
```suggestion
В ostis-системах все \textit{логические связки} (такие как \textit{отрицание*} ($\lnot$) , \textit{импликация*} ($\to$) и т.д.) и \textit{кванторами} (такие как \textit{квантор всеобщности} ($\forall$) и \textit{квантор существования} ($\exists$)) являются \textit{sc-связками} соответствующих отношений. Вопрос пользователя может 
быть представлен в виде атомарной логической формулы или \textit{конъюнкцией*} нескольких \textit{логических формул} (см. \scncite{Golenkov2014b}, \scncite{Rujiang2011}). Все sc-связки и sc-коннекторы образуют дерево, которое полностью описывает логическую последовательность между связками и кванторами в логической формуле. Поскольку sc-структура, содержащая атомарную логическую формулу, связана с соответствующим sc-связкой, пока определена позиция каждой sc-связки и sc-структуры в графе, можно определить позицию каждой переменной sc-узла в этом графе. В данной подглаве предлагается подход к нумерации каждой sc-связки и sc-структуры в семантическом графе в соответствии со стратегией поиска в глубину (DFS). Процесс работы данного подхода показан ниже:
```

2023-03-23 23:54 UTC, NikitaZotov commented on author/part7/chapter_learning_systems/section_semantic_model_and_knowledge_control.tex
> +Поскольку семантические графы, используемые для описания ответов на вопросы на толкование определений, построены на основе логических формул, в семантические графы включены переменные sc-узлов (эквив
```suggestion
Для того чтобы рассчитать подобие между семантическими графами, наиболее важным шагом является установление отношений отображения потенциальных эквивалентных пар переменных sc-узлов между графами. Поэтому на основе существующих методов отображения онтологий (например, ASMOW, RiMOM и др.) предлагается подход к установлению отношений отображения потенциальных эквивалентных пар переменных sc-узлов между семантическими графами в соответствии с семантическими структурами (различными sc-конструкциями) (см. \scncite{Zeng2021}, \scncite{Sun2020}, \scncite{Rujiang2011}).
```

2023-03-23 23:54 UTC, NikitaZotov commented on author/part7/chapter_learning_systems/section_semantic_model_and_knowledge_control.tex
> +	\item начиная с корня древовидной структуры, состоящей из sc-кортежей, каждый узел sc-кортежа в дереве нумеруется по очереди в соответствии со стратегией DFS и приоритетом текущего sc-узла (например
```suggestion
	\item каждая sc-связка и sc-структура в дереве нумеруется по очереди в соответствии со стратегией DFS и приоритетом текущей sc-связки (например, приоритет sc-связки ``если' ''\ выше, чем приоритет sc-структуры ``то' '') (последовательность нумерации начинается с 0);
```

2023-03-23 23:54 UTC, NikitaZotov commented on author/part7/chapter_learning_systems/section_semantic_model_and_knowledge_control.tex
> +	\item в соответствии с последовательностью нумерации sc-кортежей, каждый sc-кортеж в дереве обходится от малого к большому, а sc-структура, связанная с текущим sc-кортежем, нумеруется при обходе (по
```suggestion
	\item в соответствии с последовательностью нумерации sc-связок, каждый sc-связка в дереве обходится от малого к большому, а sc-структура, связанная с текущей sc-связкой, нумеруется при обходе (последовательность нумерации начинается с 1).
```

2023-03-23 23:54 UTC, NikitaZotov commented on author/part7/chapter_learning_systems/section_semantic_model_and_knowledge_control.tex
> +	\item использование двух шаблонов для поиска всех соответствующих семантических фрагментов в базе знаний и проверка наличия двух семантических фрагментов в этих найденных семантических фрагментах, к
```suggestion
	\item использование двух шаблонов для поиска всех изоморфных семантических фрагментов в базе знаний и проверка наличия двух фрагментов пользователя в этих найденных фрагментах, которые соответственно включены в стандартный ответ и ответ пользователя. Если существуют такие два фрагмента (соответствие различным шаблонам), выполняется следующий шаг;
```

2023-03-23 23:54 UTC, NikitaZotov commented on author/part7/chapter_learning_systems/section_semantic_model_and_knowledge_control.tex
> +	\item декомпозиция семантического графа стандартного ответа и семантического графа ответа пользователя на подструктуры в соответствии с правилами представления фактических знаний и логических знаний
надо везде убрать семантические графы

2023-03-23 23:54 UTC, NikitaZotov commented on author/part7/chapter_learning_systems/section_semantic_model_and_knowledge_control.tex
> +	\item нумерация sc-кортежей и sc-структур в семантических графах ответов, соответственно, и установление отношений отображения потенциальных эквивалентных пар переменных sc-узлов между семантическим
вместо sc-кортежей лучше использовать sc-связки

2023-03-23 23:54 UTC, NikitaZotov commented on author/part7/chapter_learning_systems/sec_general_principles_automation_educational_activities.tex
> +	\scnheader{обучаемость}
дублируется с главами 1.1 и 1.2

2023-03-23 23:54 UTC, NikitaZotov commented on author/part7/chapter_learning_systems/sec_general_principles_automation_educational_activities.tex
> +	\scnheader{интеллектуальная компьютерная система}
всё это тоже дублируется. Нужно интегрировать с 1.1 и 1.2

2023-03-24 20:42 UTC, ShunkevichDV requested changes
Хотя бы устранить дублирование информации в разных файлах с похожими названиями

2023-03-24 20:42 UTC, ShunkevichDV commented on author/part7/chapter_learning_systems.tex
> +\section*{Введение к Главе~\ref{chapter_learning_systems}}
```suggestion
\section*{Введение в Главу~\ref{chapter_learning_systems}}
```

2023-03-24 20:42 UTC, ShunkevichDV commented on author/part7/chapter_learning_systems.tex
> +\section*{Заключение Главе~\ref{chapter_learning_systems}}
```suggestion
\section*{Заключение Главы~\ref{chapter_learning_systems}}
```

2023-03-24 20:43 UTC, ShunkevichDV commented
В остальном согласен с Никитой

2023-03-27 07:48 UTC, ShunkevichDV approved these changes
На текущем этапе считаю, что нужно мержить, а потом уже согласовывать вместе с ВВ и НА

2023-03-27 11:15 UTC, NikitaZotov approved these changes

2023-03-27 11:16 UTC, merged