Feature/component manager
ostis-ai/monography2022 pull request #165
Opened 2023-03-19 16:51 UTC by MksmOrlov

2023-03-19 17:14 UTC, NikitaZotov approved these changes

2023-03-19 19:36 UTC, MikhailSadovsky approved these changes

2023-03-20 10:26 UTC, AlexandrZagorskiy approved these changes

2023-03-20 10:26 UTC, AlexandrZagorskiy commented on author/part5/figures/set_neighbourhood.png
Отношение от класса множества к разбиению не должно быть связкой?

2023-03-20 10:26 UTC, AlexandrZagorskiy commented on author/part5/figures/set_neighbourhood.png
Отношение от класса множества к разбиению не должно быть связкой?

2023-03-20 10:26 UTC, AlexandrZagorskiy commented on author/part5/figures/specification_storage_addresses.png
Узел с идентификатором "Хранилище спецификаций Метасистемы OSTIS" имеет выходящие дуги принадлежности с ролями "спецификации..." к узлам. Визуально эти узлы должны быть связками, по аналогии с "Хранилище спецификаций менеджера компонентов"

2023-03-20 10:26 UTC, AlexandrZagorskiy approved these changes

2023-03-20 10:41 UTC, AlexandrZagorskiy commented on author/part6/chapter_interpreter.tex
> +\scnidtf{\scnqq{пустая} ostis-система}
Что такое \scnqq?

2023-03-20 11:24 UTC, MksmOrlov commented on author/part6/chapter_interpreter.tex
> +\scnidtf{\scnqq{пустая} ostis-система}
кавычки

2023-03-20 11:26 UTC, MksmOrlov commented on author/part5/figures/set_neighbourhood.png
Можно уточнить до связки, да

2023-03-20 11:27 UTC, MksmOrlov commented on author/part5/figures/specification_storage_addresses.png
Тут у них элементы не изображены, не захотел делать связки пустыми

2023-03-20 23:51 UTC, KsenBantsevich approved these changes

2023-03-23 06:08 UTC, AlexandrZagorskiy approved these changes

2023-03-24 06:15 UTC, AlexandrZagorskiy approved these changes

2023-03-24 20:24 UTC, ShunkevichDV requested changes

2023-03-24 20:24 UTC, ShunkevichDV commented on author/part5/chapter_library.tex
> +			\scnhaselement{Агент подсчёта мощности множества}
Может Абстрактный sc-агент?

2023-03-24 20:24 UTC, ShunkevichDV commented on author/part5/chapter_library.tex
>  		\scnsuperset{атомарный агент обработки знаний}
нет такого термина, есть "атомарный абстрактный sc-агент"

2023-03-24 20:24 UTC, ShunkevichDV commented on author/part5/chapter_library.tex
> +На рисунке \nameref{fig:component_optional_specification_example} изображена необязательная часть спецификации, необходимой для установки sc-агента поиска кратчайшего пути в графе. Полная спецификаци
```suggestion
На рисунке \nameref{fig:component_optional_specification_example} изображена необязательная часть спецификации, необходимой для установки sc-агента поиска кратчайшего пути в графе. Полная спецификация компонента является результатом объединения обязательной и необязательной частей. Другие примеры спецификаций многократно используемых компонентов ostis-систем описаны в \textit{\ref{gis_components}~\nameref{gis_components}}.
```

2023-03-24 20:24 UTC, ShunkevichDV commented on author/part5/chapter_library.tex
> +На рисунке \nameref{fig:component_optional_specification_example} изображена необязательная часть спецификации, необходимой для установки sc-агента поиска кратчайшего пути в графе. Полная спецификаци
Слово параграф не нужно, там значок ставится

2023-03-24 20:24 UTC, ShunkevichDV commented on author/part5/chapter_library.tex
> +\scnrelfrom{минимальные функциональные возможности}{минимальные функциональные возможности менеджера компонентов}
```suggestion
\scnrelfrom{минимальные функциональные возможности}{Минимальные функциональные возможности менеджера компонентов}
```

2023-03-24 20:24 UTC, ShunkevichDV commented on author/part5/chapter_library.tex
> +\scnrelfrom{расширенные функциональные возможности}{расширенные функциональные возможности менеджера компонентов}
```suggestion
\scnrelfrom{расширенные функциональные возможности}{Расширенные функциональные возможности менеджера компонентов}
```

2023-03-24 20:24 UTC, ShunkevichDV commented on author/part5/chapter_library.tex
> +Для того, чтобы создать новую ostis-систему "с нуля"{}, используя \textit{ostis-платформу} (см. Параграф \ref{sec_interpreter_ostis_platform}~\nameref{sec_interpreter_ostis_platform}), необходимо уст
Везде поубирать слово Параграф

2023-03-26 11:06 UTC, ShunkevichDV approved these changes

2023-03-26 11:28 UTC, merged