Chapter 4.3. Audio interfaces figures
ostis-ai/monography2022 pull request #166
Opened 2023-03-19 16:58 UTC by delfvad

2023-03-23 23:21 UTC, NikitaZotov requested changes

2023-03-23 23:21 UTC, NikitaZotov commented on author/part4/chapter_audio_interfaces.tex
> +Для достижения поставленной цели предлагается прибегнуть к подходу на основе принципов лежащих в основе ``Стандарта открытой технологии онтологического проектирования, производства и эксплуатации сем
Думаю, что это предложение надо убрать

2023-03-23 23:21 UTC, NikitaZotov commented on author/part4/chapter_audio_interfaces.tex
> +В качестве формальной основы для кодирования различной информации в базе знаний используется \text{SC-код}, тексты которого (sc-тексты) записываются в виде \textit{семантических сетей} с базовой теор
Это надо убрать

2023-03-23 23:21 UTC, NikitaZotov commented on author/part4/chapter_audio_interfaces.tex
> +Поскольку аудиоинтерфейс ИКС нового поколения должен иметь архитектуру, соответсвующую общим правилам построения OSTIS-систем, можно выделить и формализовать следующие основные его части:
Аббревиатуры не вводим, надо писать полностью - интеллектуальные компьютерные системы нового поколения. При этом понятия нужно выделять через textit, то есть курсивом

2023-03-23 23:21 UTC, NikitaZotov commented on author/part4/chapter_audio_interfaces.tex
> +Согласно общим принципам организации интерфейсов ostis-систем, изложенным в  \textit{Главе\ref{chapter_interfaces}~\nameref{chapter_interfaces}} аудио- и речевой интерфейс относятся к подмножеству SI
```suggestion
Согласно общим принципам организации интерфейсов ostis-систем, изложенным в  \textit{Главе \ref{chapter_interfaces}}, аудио- и речевой интерфейс относятся к подмножеству SILK-интерфейсов \textit{пользовательских интерфейсов} \textit{интеллектуальных компьютерных систем}. 
```

2023-03-23 23:21 UTC, NikitaZotov commented on author/part4/chapter_audio_interfaces.tex
> +Согласно общим принципам организации интерфейсов ostis-систем, изложенным в  \textit{Главе\ref{chapter_interfaces}~\nameref{chapter_interfaces}} аудио- и речевой интерфейс относятся к подмножеству SI
Возможно нужно уточнить главу до параграфа этой главы, в котором говорится про SILK-интерфейсы

2023-03-23 23:21 UTC, NikitaZotov commented on author/part4/chapter_audio_interfaces.tex
> +В зависимости от способа математического описания обрабатываемого сигнала в  OSTIS-системе, можно определить следующие их классы:
```suggestion
В зависимости от способа математического описания обрабатываемого сигнала в OSTIS-системе, можно определить следующие их классы:
```

2023-03-23 23:21 UTC, NikitaZotov commented on author/part4/chapter_audio_interfaces.tex
> +Формализуем также основные понятия связанные с характеристиками самого сигнала, по следующим основным его атрибутам \textit{\nameref{fig:speech-structure-segment-suprasegment}}:
```suggestion
Формализуем также основные понятия, связанные с характеристиками самого сигнала, по следующим основным его атрибутам \textit{\nameref{fig:speech-structure-segment-suprasegment}}:
```

2023-03-23 23:21 UTC, NikitaZotov commented on author/part4/chapter_audio_interfaces.tex
> +  \item Создание автоматизированных и автоматических средств извлечения знаний из существующих источников информации, в первую очередь текстов на естественном языке. К видам документов в которых, сод
нужны, наоборот, scncite'ы

2023-03-24 21:26 UTC, ShunkevichDV requested changes

2023-03-24 21:26 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +Для достижения поставленной цели предлагается прибегнуть к подходу на основе принципов лежащих в основе ``Стандарта открытой технологии онтологического проектирования, производства и эксплуатации сем
Да

2023-03-24 21:26 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
>  \end{textitemize}
Да, все, что касается общих принципов OSTIS, нужно убирать

2023-03-24 21:26 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +Поскольку аудиоинтерфейс ИКС нового поколения должен иметь архитектуру, соответсвующую общим правилам построения OSTIS-систем, можно выделить и формализовать следующие основные его части:
```suggestion
Поскольку аудиоинтерфейс интеллектуальных компьютерных систем нового поколения должен иметь архитектуру, соответсвующую общим правилам построения ostis-систем, можно выделить и формализовать следующие основные его части: 
```

2023-03-24 21:26 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +Представленные выше принципы в совокупности позволяют осуществлять конвергенцию и интеграцию компонентов как на уровне подсистемы аудиоинтерфейса так и на уровне всей ИКС в целом, что в свою очередь
```suggestion
Представленные выше принципы в совокупности позволяют осуществлять конвергенцию и интеграцию компонентов как на уровне подсистемы аудиоинтерфейса так и на уровне всей ИКС в целом, что в свою очередь позволяет "перевести"{} \textit{интеллектуальную информационную систему} в класс гибридных, \textit{интероперабельных} и \textit{семантически совместимых систем}.
```

2023-03-24 21:26 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +В зависимости от способа математического описания обрабатываемого сигнала в  OSTIS-системе, можно определить следующие их классы:
```suggestion
В зависимости от способа математического описания обрабатываемого сигнала в ostis-системе, можно определить следующие их классы:
```

2023-03-24 21:26 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +В зависимости от способа математического описания обрабатываемого сигнала в  OSTIS-системе, можно определить следующие их классы:
Везде ostis-система пишем маленькими

2023-03-24 21:26 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +Преведём формализованное представление некоторых из обозначенных выше понятий:
```suggestion
Приведём формализованное представление некоторых из обозначенных выше понятий:
```

2023-03-24 21:26 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +\scnheader{характеристики аудиосигнала}
```suggestion
\scnheader{характеристика аудиосигнала}
```

2023-03-24 21:26 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
>  \scnheader{характеристики речевого сигнала}
как минимум все понятия мы пишем в единственном числе

2023-03-24 21:26 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +  \item Создание автоматизированных и автоматических средств извлечения знаний из существующих источников информации, в первую очередь текстов на естественном языке. К видам документов в которых, сод
Да

2023-03-26 15:22 UTC, delfvad commented on author/part4/chapter_audio_interfaces.tex
> +Для достижения поставленной цели предлагается прибегнуть к подходу на основе принципов лежащих в основе ``Стандарта открытой технологии онтологического проектирования, производства и эксплуатации сем
C этим не согласен, коллеги, ибо посыпется семантика главы. =)

2023-03-26 17:41 UTC, ShunkevichDV requested changes

2023-03-26 17:41 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +В качестве технологической основы для реализации предлагаемого подхода будет использоваться Технология OSTIS (см. \scncite{Standart2021}). Системы, построенные на основе Технологии OSTIS, названы ost
Ну вот как минимум фразы про то, что такое ostis-системы это уже явно лишнее

2023-03-26 17:41 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
>  Ориентация данной работы на Технологию OSTIS обусловлена ее следующими основными преимуществами:
"Данной работы" плохая фраза, у нас вся монография про Технологию OSTIS. Да и весь список надо немного подправить, может быть в духе - Применения Технологии OSTIS для разработки аудио интерфейсов дает следующие преимущества: и дальше немного исправленный список

2023-03-26 17:41 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +Представленные выше принципы в совокупности позволяют осуществлять конвергенцию и интеграцию компонентов как на уровне подсистемы аудиоинтерфейса так и на уровне всей \textit{интеллектуальных компьют
Что-то не так с падежами

2023-03-27 16:24 UTC, NikitaZotov requested changes

2023-03-27 16:24 UTC, NikitaZotov commented on author/part4/chapter_audio_interfaces.tex
> +Для достижения поставленной цели предлагается прибегнуть к подходу на основе принципов лежащих в основе ``Стандарта открытой технологии онтологического проектирования, производства и эксплуатации сем
и так далее

2023-03-29 15:23 UTC, ShunkevichDV approved these changes

2023-03-29 15:23 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +    \item появление широкого спектра продуктов на основе речевого интерфейса, получивших массовое распространение. В первую очередь это персональные голосовые ассистенты, таких как  «Alexa» (Amazon),
```suggestion
    \item появление широкого спектра продуктов на основе речевого интерфейса, получивших массовое распространение. В первую очередь это персональные голосовые ассистенты, таких как  ``Alexa'' (Amazon), ``Siri'' (Apple), ``Сortana'' (MicroSoft), ``Алиса'' (Yandex) (см. \scncite{Bellegarda2014}, \scncite{Lemley2017}, \scncite{Hoy2018});
```

2023-03-29 15:23 UTC, ShunkevichDV commented on author/part4/chapter_audio_interfaces.tex
> +Реализация подхода, предложенного в работе, позволит обеспечить свойства унификации, семантической совместимости и интероперабельности, при разработке аудио и речевых интерфейсов, (своеобразный анало
```suggestion
Реализация подхода, предложенного в данной главе, позволит обеспечить свойства унификации, семантической совместимости и интероперабельност, при разработке аудио и речевых интерфейсов, (своеобразный аналог модели OSI/ISO в области проектирования интерфейсов \textit{интеллектуальных компьютерных систем}), что в итоге позволит существенным образом сократить издержки при создании интеллектуальных компьютерных систем нового поколения для решении сложных комплексных задач.
```

2023-03-29 15:30 UTC, NikitaZotov approved these changes

2023-03-29 15:31 UTC, merged