Add information about metasystem
ostis-ai/monography2022 pull request #168
Opened 2023-03-20 23:33 UTC by KsenBantsevich

2023-03-22 07:40 UTC, NikitaZotov commented on author/part7/chapter_ims_standard.tex
> +ostis-системой в рамках Экосистемы OSTIS.
```suggestion
Для фиксации текущего состояния Технологии OSTIS, а также для организации ее эффективного использования и ее перманентного совершенствования с участием ученых, работающих в области искусственного интеллекта, и инженеров, разрабатывающих семантические компьютерные системы различного назначения, в состав \textit{Экосистемы OSTIS} вводится Метасистема OSTIS, назначение которой делает ее ключевой ostis-системой в рамках Экосистемы OSTIS.
```

2023-03-22 07:40 UTC, NikitaZotov commented on author/part7/chapter_ims_standard.tex
> +Важнейшим направлением \textit{Метасистемы OSTIS} и, соответственно, важнейшим направлением применения \textit{Стандарта OSTIS}, подробно описанного в \ref{sec_standard}, является использование их в
```suggestion
Важнейшим направлением \textit{Метасистемы OSTIS} и, соответственно, важнейшим направлением применения \textit{Стандарта OSTIS}, подробно описанного в \ref{sec_standard}, является использование их в качестве комплексного интегрированного компьютерного учебного пособия по специальности "Искуственный интеллект"{}. Для этого устанавливается связь между разделами \textit{Стандарта OSTIS} и программами различных \textit{учебных дисциплин} указанной специальности. Важно подчеркнуть при этом: \textit{Стандарт OSTIS} содержит достаточно полный сравнительный анализ с различными альтернативными подходами, то есть ни в коем случае не ограничивается рассмотрением \uline{только} \textit{Технологией OSTIS}.
```

2023-03-23 23:24 UTC, NikitaZotov requested changes

2023-03-23 23:24 UTC, NikitaZotov commented on author/part7/chapter_ims_standard.tex
> +Для фиксации текущего состояния Технологии OSTIS, а также для организации ее эффективного использования и ее перманентного совершенствования с участием ученых, работающих в области искусственного инт
все понятия нужно выделять курсивом

2023-03-23 23:24 UTC, NikitaZotov commented on author/part7/chapter_ims_standard.tex
> +Для фиксации текущего состояния Технологии OSTIS, а также для организации ее эффективного использования и ее перманентного совершенствования с участием ученых, работающих в области искусственного инт
сущности (экземпляры понятий) тоже

2023-03-23 23:24 UTC, NikitaZotov commented on author/part7/chapter_ims_standard.tex
> +	\scnidtf{Intelligent MetaSystem for ostis-systems design}
```suggestion
```

2023-03-23 23:24 UTC, NikitaZotov commented on author/part7/chapter_ims_standard.tex
> +	\scnidtf{OSTIS-система автоматизации проектирования ostis-систем}
```suggestion
	\scnidtf{ostis-система автоматизации проектирования ostis-систем}
```

2023-03-23 23:24 UTC, NikitaZotov commented on author/part7/chapter_ims_standard.tex
> +Метасистема OSTIS -- Метасистема, являющаяся:
```suggestion
Метасистема OSTIS -- метасистема, являющаяся:
```

2023-03-23 23:24 UTC, NikitaZotov commented on author/part7/chapter_ims_standard.tex
> +		\scnitem{Sc-модель Метасистемы IMS.ostis}
Везде IMS.ostis надо заменить на OSTIS

2023-03-24 22:05 UTC, ShunkevichDV requested changes

2023-03-24 22:05 UTC, ShunkevichDV commented on author/part7/chapter_ims_standard.tex
> +	\scnidtf{Intelligent MetaSystem for ostis-systems design}
А что не так-то

2023-03-24 22:05 UTC, ShunkevichDV commented on author/part7/chapter_ims_standard.tex
> +	\scnnote{При \textit{Разработке Базовой Комплексной технологии проектирования интеллектуальных компьютерных систем} (точнее ostis-систем) средством автоматизации этой деятельности является не вся \t
```suggestion
	\scnnote{При \textit{Разработке Базовой Комплексной технологии проектирования интеллектуальных компьютерных систем} (точнее ostis-систем) средством автоматизации этой деятельности является не вся \textit{Метасистема OSTIS}, а только ее часть – входящая в состав \textit{Метасистемы OSTIS} типовая \textit{Встраиваемая ostis-система поддержки реижиниринга ostis-систем}, которая поддерживает деятельность разработчиков базы знаний \textit{Метасистемы OSTIS}. Это обусловлено тем, что вся деятельность по \textit{Разработке Базовой Комплексной технологии проектирования интеллектуальных компьютерных систем} (ostis-систем) сводится к разработке (инженирингу) и обновлению (совершенствованию, реинжинирингу) \textit{Базы знаний Метасистемы OSTIS}).}
```

2023-03-24 22:05 UTC, ShunkevichDV commented on author/part7/chapter_ims_standard.tex
> +	\scnnote{При \textit{Разработке Базовой Комплексной технологии проектирования интеллектуальных компьютерных систем} (точнее ostis-систем) средством автоматизации этой деятельности является не вся \t
У нас нет термина "Разработка Базовой Комплексной технологии проектирования интеллектуальных компьютерных систем", лучше перефразировать попроще, типа разработка Технологии OSTIS
Здесь и в других местах

2023-03-24 22:05 UTC, ShunkevichDV commented on author/part7/chapter_ims_standard.tex
> +Принципы технической реализации Метасистемы IMS.ostis полностью совпадают с принципами технической реализации прикладных интеллектуальных систем, разрабатываемых с помощью этой метасистемы.
Пересмотреть по всему тексту: Метасистема IMS.ostis -> Метасистема OSTIS

2023-03-24 22:05 UTC, ShunkevichDV commented on author/part7/chapter_ims_standard.tex
> +Важнейшим направлением \textit{Метасистемы OSTIS} и, соответственно, важнейшим направлением применения \textit{Стандарта OSTIS}, подробно описанного в \ref{sec_standard}, является использование их в
лучше еще добавить nameref

2023-03-27 16:31 UTC, NikitaZotov approved these changes

2023-03-28 08:32 UTC, ShunkevichDV approved these changes

2023-03-28 08:32 UTC, ShunkevichDV commented on author/part7/chapter_ims_standard.tex
> -	\item порталом знаний по Технологии OSTIS, обеспечивающим:
Запятая не там

2023-03-28 08:32 UTC, ShunkevichDV commented on biblio.bib
> +	shorthand    = {Golenkov.V.V..tStandOICSKCCS-2018ст},
Точка не надо

2023-03-28 17:05 UTC, merged