OSTIS Ecosystem integration with third-party services
ostis-ai/monography2022 pull request #170
Opened 2023-03-21 17:02 UTC by AlexandrZagorskiy

2023-03-23 23:09 UTC, NikitaZotov requested changes

2023-03-23 23:09 UTC, NikitaZotov commented on author/part7/chapter_integration.tex
> +Важно проектировать не только саму Экосистему OSTIS как форму реализации Общества 5.0, но и процесс поэтапного перехода от современной глобальной сети компьютерных систем к глобальной сети ostis-сист
Важно проектировать процесс?

2023-03-23 23:09 UTC, NikitaZotov commented on author/part7/chapter_integration.tex
> +Важно проектировать не только саму Экосистему OSTIS как форму реализации Общества 5.0, но и процесс поэтапного перехода от современной глобальной сети компьютерных систем к глобальной сети ostis-сист
Предлагаю - "Важным является не только сама Экосистема OSTIS как форма реализации Общества 5.0, но и процесс поэтапного перехода от современной глобальной сети компьютерных систем к глобальной сети ostis-систем (т.е. к Экосистеме OSTIS)."

2023-03-23 23:09 UTC, NikitaZotov commented on author/part7/chapter_integration.tex
> +Важно проектировать не только саму Экосистему OSTIS как форму реализации Общества 5.0, но и процесс поэтапного перехода от современной глобальной сети компьютерных систем к глобальной сети ostis-сист
Или как-то по-другому

2023-03-23 23:09 UTC, NikitaZotov commented on author/part7/chapter_integration.tex
> +Технология OSTIS обеспечивает основу для разработки сложных систем и их беспрепятственной интеграции в существующие услуги и ресурсы. Система разработана для создания комплексной Экосистемы, которая
```suggestion
Технология OSTIS обеспечивает основу для разработки сложных систем и их беспрепятственной интеграции с существующими услугами и ресурсами. Система разработана для создания комплексной Экосистемы, которая может поддерживать различные приложения, включая управление информацией, анализ данных, принятие решений и автоматизацию.
```

2023-03-23 23:09 UTC, NikitaZotov commented on author/part7/chapter_integration.tex
> +Технология OSTIS обеспечивает основу для разработки сложных систем и их беспрепятственной интеграции в существующие услуги и ресурсы. Система разработана для создания комплексной Экосистемы, которая
Какая система разработана?

2023-03-23 23:09 UTC, NikitaZotov commented on author/part7/chapter_integration.tex
> +Цель данного раздела - дать всесторонний анализ, представить аргументы в пользу внедрения современных систем и сервисов в Экосистему OSTIS.
```suggestion
Цель данного раздела - дать всесторонний анализ и представить аргументы в пользу внедрения современных систем и сервисов в Экосистему OSTIS.
```

2023-03-23 23:09 UTC, NikitaZotov commented on author/part7/chapter_integration.tex
> +	\item Улучшение скорости и качества разработки. Интеграция различных сервисов и ресурсов в Экосистему OSTIS может помочь ускорить процесс разработки новых приложений, а также повысить качество их ре
```suggestion
	\item Улучшение скорости и качества разработки. Интеграция различных сервисов и ресурсов в Экосистему OSTIS может помочь ускорить процесс разработки новых приложений, а также повысить качество их реализации. Это связано с тем, что интеграция сервисов позволяет использовать уже существующие компоненты, что сокращает время и затраты на разработку.
```

2023-03-23 23:09 UTC, NikitaZotov commented on author/part7/chapter_integration/sec_integration_common_principles.tex
> +ostis-системы могут выполнять роль системных интеграторов различных ресурсов и сервисов, реализованных современными компьютерными системами, поскольку уровень интеллекта ostis-систем позволяет им с л
```suggestion
ostis-системы могут выполнять роль системных интеграторов различных ресурсов и сервисов, реализованных современными компьютерными системами, поскольку уровень интеллекта ostis-систем позволяет им с любой степенью детализации специфицировать интегрируемые компьютерные системы и, следовательно, достаточно адекватно "понимать", что знает и/или умеет каждая из них. Также ostis-системы способны достаточно качественно координировать деятельность стороннего ресурса и сервиса и обеспечивать релевантный поиск нужного ресурса и сервиса. 
```

2023-03-24 06:38 UTC, AlexandrZagorskiy commented on author/part7/chapter_integration.tex
> +Важно проектировать не только саму Экосистему OSTIS как форму реализации Общества 5.0, но и процесс поэтапного перехода от современной глобальной сети компьютерных систем к глобальной сети ostis-сист
Думаю неплохо, применю

2023-03-24 06:48 UTC, AlexandrZagorskiy commented on author/part7/chapter_integration.tex
> +В данном разделе рассматривается значение интеграции Экосистемы OSTIS с современными сервисами и информационными ресурсами, а также потенциальные преимущества такой интеграции. Рассмотрены важность э
Просто убрал, ничего не потерял

2023-03-24 16:39 UTC, NikitaZotov commented on author/part7/chapter_integration.tex
> +Важным является не только сама Экосистема OSTIS как форма реализации Общества 5.0, но и процесс поэтапного перехода от современной глобальной сети компьютерных систем к глобальной сети ostis-систем (
```suggestion
Важным является не только сама Экосистема OSTIS как форма реализации Общества 5.0, но и процесс поэтапного перехода от современной глобальной сети компьютерных систем к глобальной сети ostis-систем (то есть к Экосистеме OSTIS).
```

2023-03-24 16:39 UTC, NikitaZotov commented on author/part7/chapter_integration.tex
> +Важным является не только сама Экосистема OSTIS как форма реализации Общества 5.0, но и процесс поэтапного перехода от современной глобальной сети компьютерных систем к глобальной сети ostis-систем (
И так далее

2023-03-24 22:08 UTC, ShunkevichDV approved these changes
Норм с учетом замечаний Никиты

2023-03-24 22:08 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_common_principles.tex
> +Процесс интеграции требует глубокого понимания базовых принципов технологии OSTIS.
```suggestion
Процесс интеграции требует глубокого понимания базовых принципов Технологии OSTIS. 
```

2023-03-31 12:28 UTC, ShunkevichDV approved these changes

2023-03-31 12:28 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_services.tex
> +    \item разработка \textit{агента обработки знаний}, который будет обеспечивать взаимодействие между базой знаний системы и сторонним сервисом в соответствии со спецификацией интеграции;
К этому времени уже давно введено понятие sc-агента и абстрактного sc-агента, лучше использовать их

2023-03-31 12:48 UTC, merged