Chapter 5.4 interface analisys
ostis-ai/monography2022 pull request #171
Opened 2023-03-21 19:50 UTC by aleksashaz

2023-03-24 00:04 UTC, NikitaZotov requested changes

2023-03-24 00:04 UTC, NikitaZotov commented on author/part5/chapter_ui_design.tex
> +подсистем уже имелось в библиотеке компонентов пользовательских интерфейсов.
```suggestion
подсистем уже имелось в \textit{Библиотеке многократно используемых компонентов пользовательских интерфейсов ostis-систем}.
```

2023-03-24 00:04 UTC, NikitaZotov commented on author/part5/chapter_ui_design.tex
> +подсистем уже имелось в библиотеке компонентов пользовательских интерфейсов.
Все понятия нужно выделять курсивом, то есть textit

2023-03-24 00:04 UTC, NikitaZotov commented on author/part5/chapter_ui_design.tex
> +пользовательские интерфейсы. Большое число компонентов создает проблему их хранения и поиска. Чтобы решить эту проблему, в технологию включена библиотека совместимых компонентов пользовательских инте
\textit{Библиотека многократно используемых компонентов пользовательских интерфейсов ostis-систем}

2023-03-27 09:07 UTC, ShunkevichDV approved these changes

2023-03-27 09:09 UTC, ShunkevichDV requested changes

2023-03-27 09:09 UTC, ShunkevichDV commented on author/part5/chapter_ui_design.tex
> +Машина обработки знаний состоит из следующего набора операций:
Нет термина машина обработки, есть решатель задач
Нет термина операция, есть sc-агент
Вычитайте внимательнее

2023-03-27 16:27 UTC, NikitaZotov commented on author/part5/chapter_ui_design.tex
> +В настоящее время организация взаимодействия пользователя с компьютерной системой основана на парадигме \textbf{грамотного пользователя},	который знает, как управлять системой и несёт полную ответств
```suggestion
В настоящее время организация взаимодействия пользователя с компьютерной системой основана на парадигме \textbf{грамотного пользователя}, который знает, как управлять системой и несёт полную ответственность за качество взаимодействия с ней.
```

2023-03-31 12:42 UTC, ShunkevichDV requested changes

2023-03-31 12:42 UTC, ShunkevichDV commented on author/part5/chapter_ui_design.tex
> +ализированную подсистему для решения \textit{интерфейсных задач} пользователя, состоящую из \textit{базы знаний} и \textit{решателя задач}.
Прилепить к предыдущей строчке

2023-03-31 12:42 UTC, ShunkevichDV commented on author/part5/chapter_ui_design.tex
> +Описание модели \textit{базы знаний} и \textit{решателя задач} предлагается осуществлять на основе универсального унифицированного \textit{языка представления знаний}, что обеспечит \myuline{совмести
Зачем общие слова, к этому моменту уже есть SC-код и модели баз знаний и решателей задач, лучше всего сослаться прямо на соответствующие главы

2023-03-31 12:42 UTC, ShunkevichDV commented on author/part5/chapter_ui_design.tex
> +\textbf{Задачно-ориентированная декомпозиция}
декомпозиция чего?

2023-03-31 12:42 UTC, ShunkevichDV commented on author/part5/chapter_ui_design.tex
>  \textbf{Анализ пользовательского интерфейса и его адаптации}
Может адаптациЯ?
Не совсем понимаю иначе что это значит
С другой стороны, адаптация же по идее происходит перманентно
Может быть тогда Анализ пользовательского интерфейса и возможностей его адаптации?

2023-03-31 12:42 UTC, ShunkevichDV commented on author/part5/chapter_ui_design.tex
> +Представленные методы оценки пользовательских интерфейсов могут быть применены и для оценки \textit{пользовательских интерфейсов ostis-систем}. При этом особенностью проектирования \textit{пользовате
Все нормально, но надо немного тверже - что представленные методы предлагается применять и для ostis-систем в рамках рассмотренного ранее этапа ``Название''

2023-03-31 12:42 UTC, ShunkevichDV commented on author/part5/chapter_ui_design.tex
> +	\item sc-агент поиска компонента по его спецификации;
Если речь идет про набор агентов каждой системы, то надо писать Абстрактный sc-агент. Просто sc-агент будет в конкретной отдельной системе уже

2023-03-31 16:58 UTC, ShunkevichDV approved these changes

2023-03-31 16:58 UTC, ShunkevichDV commented on author/part5/chapter_ui_design.tex
> +В рамках \textit{Библиотеки многократно используемых компонентов пользовательских интерфейсов ostis-систем} могут содержаться различные версии и модификации
Тут лишние переводы строки стоит поубирать

2023-03-31 16:58 UTC, ShunkevichDV commented on biblio.bib
> +	shorthand    = {Sadouski M..MethoaTfCIDoNICS-2022art},
```suggestion
	shorthand    = {Sadouski M..Metho aTfCIDoNICS-2022art},
```

2023-03-31 21:45 UTC, NikitaZotov requested changes

2023-03-31 21:45 UTC, NikitaZotov commented on author/part5/chapter_ui_design.tex
> +\scntext{аннотация}{Проектирование интерфейса -- это один из наиболее важных  этапов разработки любой системы.
```suggestion
\scntext{аннотация}{Проектирование интерфейса -- это один из наиболее важных этапов разработки любой системы.
```

2023-03-31 21:45 UTC, NikitaZotov commented on author/part5/chapter_ui_design.tex
> +	В рамках главы рассмотрены этапы проектирования \textit{пользовательских интерфейсов} и этапы проектирования \textit{адаптивных интеллектуальных мультимодальных пользовательских интерфейсов}.}
Большая цитата - нужно меньше

2023-03-31 21:45 UTC, NikitaZotov commented on author/part5/chapter_ui_design.tex
> +	\item создание контекста использования (идентификация и создание контекста использования -- модели пользователя, модель устройства и модель среды/платформы);
надо три дефиса

2023-03-31 21:45 UTC, NikitaZotov commented on author/part5/chapter_ui_design.tex
> +На этапе задачно-ориентированной декомпозиции пользовательского интерфейса специфицированный интерфейс разбивается на интерфейсные подсистемы, которые могут разрабатываться параллельно. Это позволяет
Не везде понятия выделены курсивом

2023-04-02 12:16 UTC, MksmOrlov requested changes
[book-505-512 (2).pdf](https://github.com/ostis-ai/monography2022/files/11132164/book-505-512.2.pdf)
Ссылку на онлайн-доступ присылал. Проблема в терминах и в дублировании и + смотрите документ "[финальные правки](https://docs.google.com/document/d/1vxN4Y3dLt-F3ac08BqHFmtMJrvsHnyRwX9HBYqPRKQQ/edit?pli=1)"

2023-04-03 20:01 UTC, ShunkevichDV approved these changes

2023-04-03 20:03 UTC, NikitaZotov approved these changes

2023-04-04 08:40 UTC, MksmOrlov requested changes
не все критические замечания из прошлого ревью исправлены, отписал в личные сообщения

2023-04-04 19:56 UTC, MikhailSadovsky commented
Библиографию добавим отдельным пром

2023-04-05 06:49 UTC, MksmOrlov requested changes
И не забыть про финальные правки. По крайней мере вижу, что ссылки другие главы не все курсивом выделены

2023-04-05 06:49 UTC, MksmOrlov commented on author/part5/chapter_ui_design.tex
> +\textit{интерфейсы}, так и специфицированные \textit{компоненты интерфейсов}. Большое число \textit{многократно используемых компонентов интерфейсов ostis-систем} создает проблему их хранения и поиск
все-таки хранение, поиск, добавление, удаление, сравнение --- это общее для всех библиотек и у меня описано. Не нужно дублировать

2023-04-05 08:51 UTC, MksmOrlov approved these changes

2023-04-05 10:48 UTC, merged