[WIP] Chapter 4.1 interfaces
ostis-ai/monography2022 pull request #173
Opened 2023-03-22 19:01 UTC by MikhailSadovsky

2023-03-23 23:10 UTC, NikitaZotov commented on author/part4/chapter_interfaces.tex
> +	\scnidtf{пользовательский интерфейс, при котором обмен информацией между компьютерной системой и пользователем осуществляется путем написания текстовых инструкций или команд.}
```suggestion
	\scnidtf{пользовательский интерфейс, при котором обмен информацией между компьютерной системой и пользователем осуществляется путем написания текстовых инструкций или команд}
```

2023-03-23 23:11 UTC, NikitaZotov commented on author/part4/chapter_interfaces.tex
> +\begin{textitemize}
лучше здесь всё сделать в виде scn-текста

2023-03-23 23:11 UTC, NikitaZotov commented on author/part4/chapter_interfaces.tex
> +На современном этапе развития Искусственного интеллекта для повышения эффективности взаимодействия необходим переход от парадигмы грамотного управления используемым инструментом к парадигме \textbf{р
```suggestion
На современном этапе развития Искусственного интеллекта для повышения эффективности взаимодействия необходим переход от парадигмы грамотного управления используемым инструментом к парадигме \textbf{равноправного сотрудничества, партнёрскому взаимодействию}  интеллектуальной компьютерной системы со своим пользователем. Дружественность пользовательского интерфейса должна заключаться в адаптивности системы к особенностям и квалификации пользователя, исключении любых проблем для пользователя в процессе диалога с интеллектуальной компьютерной системой, в перманентной заботе о совершенствовании коммуникационных навыков пользователя. Следовательно, необходимо отойти от привычной адаптации пользователя к системе (путем обучения ее использованию) в сторону адаптации самого интерфейса под цели, задачи и характеристики конкретного пользователя в режиме реального времени \scncite{fomina}.
```

2023-03-27 09:43 UTC, ShunkevichDV requested changes

2023-03-27 09:43 UTC, ShunkevichDV commented on author/part4/chapter_interfaces.tex
> +Также в литературе можно встретить термин - адаптированный интерфейс.
```suggestion
Также в литературе можно встретить термин ``адаптированный интерфейс''. 
```

2023-03-27 09:43 UTC, ShunkevichDV commented on author/part4/chapter_interfaces.tex
> +Среди существующих \textit{онтологий модели пользователя} можно выделить онотолгию GUMO (см. \scncite{Heckmann}), в рамках которой выделяют:
```suggestion
Среди существующих \textit{онтологий модели пользователя} можно выделить онтологию GUMO (см. \scncite{Heckmann}), в рамках которой выделяют:
```

2023-03-27 09:43 UTC, ShunkevichDV commented on author/part4/chapter_interfaces.tex
> +\section{Структура интерфейсов ostis-систем}
Может быть назвать как-то типа Предлагаемый подход к организации интерфейсов ostis-систем, чтобы было видно, что это связано с прошлыми пунктами

2023-03-27 09:43 UTC, ShunkevichDV commented on author/part4/chapter_interfaces.tex
>  \textit{Пользовательский интерфейс ostis-системы} представляет собой специализированную \textit{ostis-систему}, ориентированную на решение интерфейсных задач, и имеющую в своем составе базу знаний и
Первых несколько абзацев выглядят как принципы, было бы правильнее сделать это типа как Для организации интерфейса ostis-систем предлагаются следующие принципы и дальше список, так нагляднее

2023-03-27 09:43 UTC, ShunkevichDV commented on author/part4/chapter_interfaces.tex
>  \scnheader{Компонент пользовательского интерфейса}
Почему с большой буквы?

2023-03-27 09:43 UTC, ShunkevichDV commented on author/part4/chapter_interfaces.tex
> +\scnidtf{знак фрагмента базы знаний, имеющий определённую форму внешнего представления на экране}
Знак фрагмента или знак конкретной сущности? В том плане, что может конкретный узел, или все же фрагмент целый

2023-03-27 09:43 UTC, ShunkevichDV commented on author/part4/chapter_interfaces.tex
> +\begin{textitemize}
Согласен

2023-03-27 09:43 UTC, ShunkevichDV commented on author/part4/chapter_interfaces.tex
>  Интерфейсное действие пользователя, как правило, инициирует некоторое внутреннее действие системы.
В конце главы надо сделать во-первых какое-то заключение, во-вторых подвести в конце всех параграфов хотя бы в пару предложений какие-то итоги, для чего это все было

2023-03-27 16:26 UTC, NikitaZotov commented on author/part4/chapter_interfaces.tex
> +\begin{textitemize}
Пока не исправлено

2023-03-29 13:23 UTC, ShunkevichDV approved these changes
Пока можно вмержить, но нужно обязательно потом проверить все главы на предмет того, чтобы были какие-то выводы по итогам анализа и по итогам главы

2023-03-29 17:50 UTC, MikhailSadovsky commented
Заключение и итоги добавлю в отдельном пул реквесте

2023-03-29 17:51 UTC, merged

2023-03-29 17:51 UTC, ShunkevichDV approved these changes