Add integration resources paragraph
ostis-ai/monography2022 pull request #174
Opened 2023-03-23 18:39 UTC by fail2172

2023-03-24 06:35 UTC, AlexandrZagorskiy requested changes

2023-03-24 06:35 UTC, AlexandrZagorskiy commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Проблема пополнения базы знаний не нова. Попытки ее решить предпринимались и ранее. Далее рассмотрены несколько подходов к пополнению БЗ.
```suggestion
Проблема автоматизированного пополнения базы знаний не нова. Попытки ее решить предпринимались и ранее. Далее рассмотрены несколько подходов к автоматизированному пополнению БЗ.
```

2023-03-24 06:35 UTC, AlexandrZagorskiy commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Все эти подходы так или иначе связаны с понятием RDF – модели, предложенной консорциумом W3C. Так что перед тем, как перейти к ним, стоит уделить внимание RDF.
Вот как сгенерировал начало, можешь пересмотреть и подправить на своё усмотрение:

> Принципы интеграции Экосистемы OSTIS со структурированными информационными ресурсами основаны на пополнении базы знаний системы новыми знаниями. Данная проблема актуальна уже длительное время, и для ее решения были предложены различные подходы. Один из таких подходов - использование RDF (Resource Description Framework), который является моделью данных, предложенной консорциумом W3C.
> 
> Для успешной интеграции структурированных информационных ресурсов в Экосистему OSTIS, важно уделить должное внимание пониманию и применению принципов RDF-модели, поскольку они играют ключевую роль в организации связей между различными ресурсами. RDF используется для описания ресурсов в сети Интернет, и является основой для построения семантических веб-приложений, таких как Linked Open Data.

2023-03-24 06:35 UTC, AlexandrZagorskiy commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Система наполнения БЗ будет реализована с использованием OSTIS-технологии. Технология OSTIS – комплекс (семейство) технологий, обеспечивающих проектирование, производство, эксплуатацию и реинжиниринг
Не нужно тут пояснять, это уже объяснялось на предыдущих 600 страницах)

2023-03-24 06:35 UTC, AlexandrZagorskiy commented on author/part7/chapter_integration/sec_integration_resources.tex
> +\end{textitemize}
Тут я бы тоже убрал фрагменты по описанию технологии

2023-03-24 06:35 UTC, AlexandrZagorskiy commented on author/part7/chapter_integration/sec_integration_resources.tex
> +На данном этапе оставшиеся wiki-тройки будут преобразованы с сохранением той структуры отношения, в которой находились участвовавшие в нем сущности. Это значит, что порядок элементов в итоговой конст
Такс, откуда тут взялись wiki-тройки? В начале параграфа речь шла только об rdf

2023-03-24 06:35 UTC, AlexandrZagorskiy commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Таким образом, мы получаем полностью интегрированную систему, которая способна отвечать всем запросам пользователя. Загружать информацию, производить над знаниями полезную работу, и затем выдать эти
```suggestion
Таким образом, мы получаем полностью интегрированную систему, которая способна отвечать всем запросам пользователя: загружать информацию, производить над знаниями полезную работу, и затем выдать эти знания в заданном формате.
```

2023-03-24 21:39 UTC, ShunkevichDV requested changes

2023-03-24 21:39 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Система наполнения БЗ будет реализована с использованием OSTIS-технологии. Технология OSTIS – комплекс (семейство) технологий, обеспечивающих проектирование, производство, эксплуатацию и реинжиниринг
Да, нужно убрать все, что касается общих принципов технологии

2023-03-24 21:39 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +\end{textitemize}
+

2023-03-29 13:29 UTC, ShunkevichDV requested changes

2023-03-29 13:29 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Проблема автоматизированного пополнения базы знаний не нова. Попытки ее решить предпринимались и ранее. Далее рассмотрены несколько подходов к автоматизированному пополнению БЗ.
Аббревиатуры стараемся не использовать, БЗ надо везде раскрыть и выделить курсивом как идентификатор

2023-03-29 13:29 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Система наполнения БЗ будет реализована с использованием OSTIS-технологии.
Какая система, для чего такая система?

2023-03-29 13:29 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Принципы интеграции Экосистемы OSTIS со структурированными информационными ресурсами основаны на пополнении базы знаний системы новыми знаниями. Данная проблема актуальна уже длительное время, и для
Ничего вообще не сказано о том, для чего нужно это интегрировать, что вообще можно интегрировать, каковы общие принципы этой интеграции

2023-03-29 13:29 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +    \item R2RML – это стандарт W3C для выражения настраиваемых отображений из реляционных БД в RDF. Такие отображения предоставляют возможность просматривать существующие реляционные данные в модели
Нужны библиографические ссылки на все подходы как минимум

2023-03-29 13:29 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Для решения задачи интеграции, использование OSTIS-системы целесообразно по многим причинам. Технология изначально предлагает инструменты для описания синтаксиса и семантики внешних языков. Данный ин
ostis-систем маленькими пишется

Не понятно, что значит целесообразным, если мы в принципе говорим про интеграцию в рамках Экосистемы OSTIS, понятно, что там ostis-системы используются

2023-03-29 13:29 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +    \item способность осуществлять семантическую интеграцию знаний в своей;
В своей?
И что значит семантическая интеграция

2023-03-29 13:29 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Память OSTIS-системы представляет собой семантическую сеть, в основе которой лежит графовая структура. Все элементы семантической сети являются знаками различных сущностей. Такими сущностями могут бы
Про память ostis-систем до этого уже рассказывали 500 страниц, не надо еще раз

2023-03-29 13:30 UTC, ShunkevichDV requested changes

2023-03-29 13:30 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Таким образом, мы получаем полностью интегрированную систему, которая способна отвечать всем запросам пользователя: загружать информацию, производить над знаниями полезную работу, и затем выдать эти
И что, это весь материал, который удалось найти?
Такое ощущение, что в прошлом PR было больше

Когда было замечание про WikiData, Это не значило, что надо просто выкинуть, а надо просто к нему как-то подвести

2023-04-01 18:39 UTC, ShunkevichDV requested changes

2023-04-01 18:39 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +Принципы интеграции Экосистемы OSTIS со структурированными информационными ресурсами основаны на пополнении базы знаний системы новыми знаниями. Данная проблема актуальна уже длительное время, и для
Добавить ссылки на RDF, они уже есть в bib по-моему

2023-04-01 18:39 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +    \item R2RML – это стандарт W3C для выражения настраиваемых отображений из реляционных БД в RDF. Такие отображения предоставляют возможность просматривать существующие реляционные данные в модели
Сверху ссылки добавил это хорошо, теперь нужно в тексте добавить (см. \scncite{...})

2023-04-01 18:39 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_resources.tex
> +    \item «Озеро данных» – это централизованное хранилище, которое позволяет хранить все структурированные и неструктурированные данные в любом масштабе. «Семантическое озеро данных» – это особая фор
Кавычки не те, почитай документ от меня в слаке

2023-04-01 18:39 UTC, ShunkevichDV commented on biblio.bib
> +@techreport{R2RML2012,
1. Нужно добавить shorthand, посмотри другие примеры
2. Аннотацию нужно писать так, чтобы она была полезна и воспринималась без контекста. Хотя бы поясни что такое R2RML и сайт разработчика чего

2023-04-01 18:39 UTC, ShunkevichDV commented on bibliography.tex
> +	\scnitem{Глава \ref{sec_integration_resources} \nameref{sec_integration_resources}}
Это не глава, слово Глава нужно убрать

2023-04-02 15:36 UTC, ShunkevichDV approved these changes

2023-04-02 15:51 UTC, ShunkevichDV commented
@AlexandrZagorskiy Глянь пожалуйста, я вроде исправил

2023-04-02 17:00 UTC, AlexandrZagorskiy approved these changes

2023-04-02 17:40 UTC, merged