update logic productions
ostis-ai/monography2022 pull request #180
Opened 2023-03-27 15:32 UTC by MksmOrlov

2023-03-27 15:37 UTC, ShunkevichDV requested changes

2023-03-27 15:37 UTC, ShunkevichDV commented on author/part3/chapter_logic_productions.tex
> +		\scnitem{Логический вывод}
Точно с большой буквы?

2023-03-27 15:37 UTC, ShunkevichDV commented on author/part3/chapter_logic_productions.tex
> +Технология OSTIS позволяет интегрировать любые принципы логического вывода для решения задач в интеллектуальных системах на основе общей формальной модели. Для того, чтобы использовать какую-либо нов
```suggestion
Технология OSTIS позволяет интегрировать любые принципы логического вывода для решения задач в интеллектуальных системах на основе общей формальной модели. Для того, чтобы использовать какую-либо новую или существующую модель, необходимо привести ее к предлагаемому формализму, что позволит интегрировать и синхронизировать ее с уже имеющимися в соответствующей библиотеке совместимых компонентов. Формализм SC-кода позволяет описывать широкий спектр понятий и отношений между ними, что делает его подходящим вариантом для реализации логического вывода в интеллектуальных компьютерных системах нового поколения. Также воспользоваться техникой иерархии за счёт онтологического подхода, лежащего в основе баз знаний ostis-систем. Исходя из этого предлагается следующая иерархия интегрированных предметных областей:
```

2023-03-27 15:37 UTC, ShunkevichDV commented on author/part3/chapter_logic_productions.tex
> +Технология OSTIS позволяет интегрировать любые принципы логического вывода для решения задач в интеллектуальных системах на основе общей формальной модели. Для того, чтобы использовать какую-либо нов
Также воспользоваться техникой иерархии за счёт онтологического подхода, лежащего в основе баз знаний ostis-систем. 

Вот эту фразу вообще не понял

2023-03-27 16:10 UTC, MksmOrlov commented on author/part3/chapter_logic_productions.tex
> +		\scnitem{Логический вывод}
неточно

2023-03-27 16:12 UTC, MksmOrlov commented on author/part3/chapter_logic_productions.tex
> +Технология OSTIS позволяет интегрировать любые принципы логического вывода для решения задач в интеллектуальных системах на основе общей формальной модели. Для того, чтобы использовать какую-либо нов
здесь я имею ввиду использование наследования. Вывод, справедливый для общих понятий будет справедливым и для частных по отношению к этому общему

2023-03-27 16:22 UTC, ShunkevichDV approved these changes

2023-03-28 11:41 UTC, nastatsan approved these changes

2023-03-28 19:26 UTC, merged