scn-tex: update chapter 2.3.4.3
ostis-ai/monography2022 pull request #183
Opened 2023-03-29 00:08 UTC by smousy

2023-03-29 13:40 UTC, ShunkevichDV requested changes

2023-03-29 13:40 UTC, ShunkevichDV commented on author/part2/chapter_ext_lang.tex
> +Для трансляции исходного текста в базу знаний был разработан tex2scs-translator. Каждой scn-tex команде соответствует семантическая структура, транслятор переводит текст из файлов .tex в .scs. Таким
Надо пример работы транслятора добавить

2023-03-29 13:40 UTC, ShunkevichDV commented on author/part2/chapter_ext_lang.tex
> +Полный перечень команд можно увидеть в файле scn.tex, а примеры использования команд каждого типа - в исходных текстах стандарта.
Нет такого файла больше

2023-03-29 13:40 UTC, ShunkevichDV commented on author/part2/chapter_ext_lang.tex
> +
Здесь бы хоть немного пояснить про классы команд, хотя бы про environment-ы и списки и какой-нибудь витиеватый пример со вложенными множествами из стандарта, чтобы мощность языка показать

По итогам этого можно сказать, что таким образом scn-tex позволяет записать практически любую конструкцию SCn-кода

2023-03-29 13:40 UTC, ShunkevichDV commented on author/part2/chapter_ext_lang.tex
> +Для трансляции исходного текста в базу знаний был разработан tex2scs-translator. Каждой scn-tex команде соответствует семантическая структура, транслятор переводит текст из файлов .tex в .scs. Таким
По тексту надо сделать ссылки на репозитории scn-плагина и транслятора, оформить как библиографию

2023-04-03 09:55 UTC, ShunkevichDV requested changes

2023-04-03 09:55 UTC, ShunkevichDV commented on author/part2/chapter_ext_lang.tex
> +	\item Популярный общепринятый язык для записи научно-технических текстов
Ну предполагалось, что эти пункты будут как-то перефразированы. Кто популярный? Кто строгий? Надо более понятно и развернуто написать

2023-04-03 09:55 UTC, ShunkevichDV commented on author/part2/chapter_ext_lang.tex
> +
Команды сами ничего вызывать не могут
\begin{scnindent} это не команда, это окружение, у него еще end есть

2023-04-03 09:55 UTC, ShunkevichDV commented on author/part2/chapter_ext_lang.tex
> +Исходный текст:
То код, то текст, надо одинаково

2023-04-03 09:55 UTC, ShunkevichDV commented on author/part2/chapter_ext_lang.tex
> +
Надо выводы какие-то по итогам параграфа
И все еще нужны ссылки на репозитории

2023-04-03 14:16 UTC, MksmOrlov commented on author/part2/chapter_ext_lang.tex
> +
4. Имеет множество багов, из-за которых иногда невозможно с ним работать

2023-04-07 08:49 UTC, MikhailSadovsky commented on author/part2/chapter_ext_lang.tex
> +Для трансляции исходного текста в базу знаний был разработан tex2scs-translator (см. \scncite{Ostis-tex2scs-translator2023}), который переводит фрагменты scn-tex в SCs-код. Каждой scn-tex команде соо
```suggestion
Для трансляции исходного текста в базу знаний был разработан tex2scs-translator (см. \scncite{Ostis-tex2scs-translator2023}), который переводит фрагменты scn-tex в SCs-код. Каждой scn-tex команде соответствует определенная синтаксическая конструкция SCs-кода. Таким образом, весь исходный текст Стандарта OSTIS, записанный в scn-tex, может быть протранслирован в базу знаний любой ostis-системы, которая поддерживает сборку базы знаний из sc.s-файлов. Далее рассмотрим пример работы транслятора.
```

2023-04-07 18:18 UTC, MikhailSadovsky approved these changes

2023-04-07 18:45 UTC, ShunkevichDV approved these changes

2023-04-07 18:46 UTC, merged