Ps design
ostis-ai/monography2022 pull request #189
Opened 2023-03-30 17:30 UTC by Vikort

2023-04-01 18:48 UTC, ShunkevichDV commented
Ждем ревью @MksmOrlov

2023-04-01 18:49 UTC, MksmOrlov commented
> Ждем ревью @MksmOrlov

Помню, двигаюсь

2023-04-01 21:33 UTC, MksmOrlov requested changes
[book-475-490 (1).pdf](https://github.com/ostis-ai/monography2022/files/11130638/book-475-490.1.pdf)
Ссылку на онлайн доступ в гугл диск также прислал

2023-04-02 13:01 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{Глава \ref{chapter_ps_design}~\nameref{chapter_ps_design}}
Там и раньше в главе говорится о МИК решателей

2023-04-02 13:53 UTC, MksmOrlov approved these changes
- Осталось ещё где-то 5 повторений "т. е", нужно убрать сокращение.
- **_эквивалентный компонент*_** описан в 5.1, это относится к любым компонентам, тут предлагаю убрать

2023-04-02 13:53 UTC, MksmOrlov commented on author/part5/chapter_ps_design.tex
> +    \item Как подсистема в рамках \textit{Метасистемы OSTIS}. Данный вариант использования предполагает отладку необходимых компонентов в рамках \textit{Метасистемы OSTIS} с последующим переносом их
```suggestion
    \item Как подсистема в рамках \textit{Метасистемы OSTIS}. Данный вариант использования предполагает отладку необходимых компонентов в рамках \textit{Метасистемы OSTIS} с последующим переносом их в \textit{дочернюю ostis-систему} (см. \textit{\ref{ostis_library_section}~\nameref{ostis_library_section}}).
```

2023-04-02 13:53 UTC, MksmOrlov commented on author/part5/chapter_ps_design.tex
> +Под \textit{многократно используемым абстрактным sc-агентом} подразумевается компонент, соответствующий некоторому \textit{абстрактному sc-агенту}, который может быть использован в решателях задач др
```suggestion
Под \textit{многократно используемым абстрактным sc-агентом} подразумевается компонент, соответствующий некоторому \textit{абстрактному sc-агенту}, который может быть использован в решателях задач других ostis-систем, возможно, в составе более сложных \textit{неатомарных абстрактных sc-агентов}. Спецификация многократно используемого \textit{абстрактного sc-агента} должна содержать всю информацию, необходимую для функционирования соответствующего \textit{sc-агента} в дочерней ostis-системе.
```

2023-04-02 14:46 UTC, ShunkevichDV approved these changes

2023-04-02 14:47 UTC, merged