7.3 and 7.4 review with updated glossary
ostis-ai/monography2022 pull request #192
Opened 2023-03-30 22:06 UTC by AlexandrZagorskiy

2023-04-01 22:08 UTC, AlexandrZagorskiy commented on author/part7/chapter_ecosystem/sec_ecosystem_analysis.tex
> +\end{SCn}
```suggestion
\textit{Сеть} может быть определена как система, состоящая из различных элементов, которые взаимодействуют друг с другом для передачи данных и ресурсов. Архетип \textit{сети} удобно использовать для отображения сложных процессов, взаимозависимость компонентов, экономических, социальных, экологических процессов, процессов коммуникации. В таких процессах нет начала или конца, всё является центром. \textit{Сеть} является единственной топологией, способной к безграничному расширению или самостоятельному обучению, остальные топологии имеют собственные ограничения.
```

2023-04-02 17:59 UTC, ShunkevichDV requested changes

2023-04-02 17:59 UTC, ShunkevichDV commented on author/part7/chapter_ecosystem.tex
> +В данном главе монографии рассмотрена архитектура \textit{Экосистемы OSTIS} и её основных компонентов, методы разработки коллективов \textit{ostis-систем}, а также типология \textit{ostis-систем}, вх
```suggestion
В данной главе монографии рассмотрена архитектура \textit{Экосистемы OSTIS} и её основных компонентов, методы разработки коллективов \textit{ostis-систем}, а также типология \textit{ostis-систем}, входящих в состав \textit{Экосистемы OSTIS}. Основная цель - предоставить полное представление о возможностях создания \textit{цифровых экосистем} на примере \textit{Экосистемы OSTIS}.
```

2023-04-02 17:59 UTC, ShunkevichDV commented on author/part7/chapter_ecosystem/sec_corporate_ostis_system.tex
> +\textit{Корпоративные системы} представляют собой программные решения, предназначенные для автоматизации бизнес-процессов и управления ресурсами и данными внутри организации. Они могут включать в себ
с маленькой буквы термины в начале предложения здесь и далее

2023-04-02 17:59 UTC, ShunkevichDV commented on author/part7/chapter_ecosystem/sec_ecosystem_analysis.tex
> +В случае, если элементы \textit{сети} сильно связны друг с другом, и при этом не имеют какого-либо центра, они образуют децентрализованную \textit{сеть}, в которой отсутствует единый центр управления
Цитатный ключ надо бы сделать просто Briscoe2012

2023-04-02 17:59 UTC, ShunkevichDV commented on author/part7/chapter_ecosystem/sec_ecosystem_analysis.tex
> +Концепция экосистемы получила все большее значение как подход к описанию взаимодействия различных самостоятельно действующих систем во внешней среде (\scncite{Boley_ecosystem_principles_2007}). Экоси
Цитатные ключи все нужно поправить короче говоря

2023-04-02 17:59 UTC, ShunkevichDV commented on author/part7/chapter_ecosystem/sec_ecosystem_structure.tex
> +Это обеспечивает существенное развитие целого ряда свойств этой \textit{компьютерной системы}, позволяющих значительно повысить \textit{уровень интеллекта} этой \textit{системы} (и, прежде всего, ее
Ну тут получается, что сам термин ostis-система это дает, надо перефразировать предыдущий абзац

2023-04-02 17:59 UTC, ShunkevichDV commented on author/part7/chapter_ecosystem/sec_ecosystem_structure.tex
> +    \scnitem{Технологии OSTIS}
```suggestion
    \scnitem{Технология OSTIS}
```

2023-04-02 17:59 UTC, ShunkevichDV commented on author/part7/chapter_ecosystem/sec_ecosystem_structure.tex
> +\textit{Иерархическим ostis-сообществом} называется такое \textit{ostis-сообщество}, по крайней мере одним из членов которого является некоторое другое \textit{ostis-сообщество}.
В начале строки с маленькой, помним

2023-04-02 18:35 UTC, AlexandrZagorskiy commented on author/part7/chapter_ecosystem/sec_ecosystem_analysis.tex
> +Концепция экосистемы получила все большее значение как подход к описанию взаимодействия различных самостоятельно действующих систем во внешней среде (\scncite{Boley_ecosystem_principles_2007}). Экоси
В следующем ПРе буду править, про это в курсе

2023-04-02 20:23 UTC, AlexandrZagorskiy commented on author/part7/chapter_ecosystem/sec_ecosystem_analysis.tex
> +Концепция экосистемы получила все большее значение как подход к описанию взаимодействия различных самостоятельно действующих систем во внешней среде (\scncite{Boley_ecosystem_principles_2007}). Экоси
Библиография ещё не готова, это из черновика взято. Я бы предложил их вынести в отдельный ПР, и ревьюить этот без учёта идентификаторов источников

2023-04-03 09:38 UTC, ShunkevichDV approved these changes

2023-04-03 09:38 UTC, ShunkevichDV commented on author/part7/chapter_integration/sec_integration_common_principles.tex
> +{\label{sec_integration_services}}
А зачем еще одни скобки?

2023-04-03 20:27 UTC, AlexandrZagorskiy commented on author/part7/chapter_integration/sec_integration_common_principles.tex
> +{\label{sec_integration_services}}
в среде ошибку не выдаёт, приятней

2023-04-03 20:27 UTC, merged