language chapters fixes
ostis-ai/monography2022 pull request #193
Opened 2023-03-31 06:30 UTC by NikiforovSergei

2023-04-05 13:10 UTC, NikitaZotov requested changes

2023-04-05 13:10 UTC, NikitaZotov commented on author/part2/chapter_inf_constr.tex
> +Для формального описания различного рода \textit{языков}, включая рассматриваемые нами \textit{языки} (\textit{SCg-код}, \textit{SCs-код}, \textit{SCn-код}) используется целый ряд метаязыковых поняти
ссылку на языку про внешние языки

2023-04-05 13:10 UTC, NikitaZotov commented on author/part4/chapter_nl_interfaces.tex
> +		\scnitem{абстрактный sc-агент лексического анализа}
Абстрактный с большой

2023-04-05 13:10 UTC, NikitaZotov commented on biblio.bib
> +	shorthand    = {Bateman.J.A.tTheorSoOiNLP-1997art},
После фамилии точка не нужна

2023-04-05 13:10 UTC, NikitaZotov commented on biblio.bib
> +	shorthand={Bateman.J.A.tGenerUMKBOaU-2002art},
```suggestion
	shorthand={Bateman J.A.tGenerUMKBOaU-2002art},
```

2023-04-05 13:10 UTC, NikitaZotov commented on biblio.bib
> +	author="Buitelaar, Paul
Что-то не то

2023-04-06 09:07 UTC, NikiforovSergei commented on author/part2/chapter_lang.tex
> +Одним из путей решения данных проблем является создание \textit{онтологий} программного обеспечения, к которым предъявляются следующие требования\cite{Pileggi2018}:
тут (в этом ПР) все что есть, Pileggi2018 конретно должен быть и .tex, и .bib уже

2023-04-06 09:08 UTC, NikiforovSergei commented on author/part2/chapter_lang.tex
>  Знак "->"{} следует читать как "состоит из"{}.
ну есть мысль ртос букально заменить его на "состоит из" текстом, т. к. у меня была анлоигя с имплкацией, напримр, тоже дернулос. нарвное так и сделаем

2023-04-06 12:04 UTC, NikitaZotov commented on author/part2/chapter_inf_constr.tex
> +\textit{\textbf{знак*}} --- \textit{бинарное ориентированное отношение}, связывающее \textit{знаковую конструкцию} со множеством всех \textit{знаков}, входящих в её состав.
меньше проблем с обработкой потом

2023-04-06 18:00 UTC, NikitaZotov requested changes

2023-04-06 18:00 UTC, NikitaZotov commented on author/part2/chapter_lang.tex
> +Так как используемый в \textit{Технологии OSTIS} \textit{язык} --- \textit{SC-код} --- обладает достаточной экспрессивностью для описания знаний любого вида, а сама технология нацелена на создание ин
```suggestion
Так как используемый в \textit{Технологии OSTIS} \textit{язык} --- \textit{SC-код} --- обладает достаточной экспрессивностью для описания знаний любого вида, а сама технология нацелена на создание интероперабельных интеллектуальных систем нового поколения, \textit{естественно-языковые интерфейсы} \textit{ostis-систем} смогут справляться с широким кругом задач по обработке текстов на естественных языках --- будь то синтез естественно-языковых текстов в целом, ведение диалога в диалоговых системах, поиск с использованием \textit{естественного языка}, выделение информации из текстов и тому подобное.
```

2023-04-07 07:37 UTC, NikiforovSergei commented on author/part2/chapter_inf_constr.tex
> +    Eсли в естественно-языковом тексте (например в цитате) используется \textit{неосновной sc-идентификатор}, то при разметке этого текста после указанного \textit{sc-идентификатора} приводится соотв
это вообще еще актуально или выпоилдить вообще?

2023-04-07 10:24 UTC, NikiforovSergei commented on author/part4/chapter_nl_interfaces.tex
> +        \scnitem{Разрешение контекста}
тут речь про "найти подходящий контекст, а если нет такого - создать"

для подобного у нас уже устоялся термин "разрешение"

2023-04-07 11:00 UTC, NikiforovSergei commented on author/part2/chapter_lang.tex
> +Наконец, \textit{онтологию} \textit{естественных языков} можно рассматривать в качестве подмножества \textit{онтологии} языков вообще (как естественных, так и искусственных и формальных), чего не дел
вставил в другео место, к первому упоминанию термина

2023-04-07 19:47 UTC, NikitaZotov requested changes

2023-04-07 19:47 UTC, NikitaZotov commented on author/part2/chapter_inf_constr.tex
> +    \begin{scnrelfromlist}{ключевое знание}
не исправлено

2023-04-07 19:47 UTC, NikitaZotov commented on author/part2/chapter_lang.tex
> +В качестве примера \textit{онтологии} в данной области можно привести COPS\cite{Lando2007}.
ссылки не оформлены

2023-04-07 19:48 UTC, NikitaZotov commented on author/part2/chapter_inf_constr.tex
> +    Eсли в естественно-языковом тексте (например в цитате) используется \textit{неосновной sc-идентификатор}, то при разметке этого текста после указанного \textit{sc-идентификатора} приводится соотв
убери

2023-04-08 08:09 UTC, NikiforovSergei commented on author/part4/chapter_nl_interfaces.tex
> +\newpage
сделал дял отправки ПДФ Владимиру Васильевичу - картнку вставляло, обрезая на половину. не уверен, что это правлиьный выход

2023-04-08 08:11 UTC, NikiforovSergei commented on author/part4/chapter_nl_interfaces.tex
> +При необходимости, \textit{библиотеку многократно используемых компонентов} \textit{естественно-языковых интерфейсов} можно дополнять знаниями о конкретных \textit{естественных языках}.
сослаться на компонентность

2023-04-08 18:51 UTC, NikitaZotov commented on author/part4/chapter_nl_interfaces.tex
> +При необходимости, \textit{библиотеку многократно используемых компонентов} \textit{естественно-языковых интерфейсов} можно дополнять знаниями о конкретных \textit{естественных языках}.
не сослался

2023-04-08 18:55 UTC, NikitaZotov approved these changes

2023-04-09 13:58 UTC, merged