3.2. New structure. Activity and technology section
ostis-ai/monography2022 pull request #195
Opened 2023-03-31 10:35 UTC by KovalM

2023-03-31 11:30 UTC, NikitaZotov requested changes

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +	\scntext{аннотация}{В главе уточнена формальная трактовка таких понятий, как действие, задача, класс действий, класс задач, метод, навык, что в совокупности позволило определить на их основе понятие
нужно будет повыделять в следующем пулл реквесте все знаки понятий и сущностей, которые используются здесь

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +	\item{текущее состояние действия;}
```suggestion
	\item{текущее состояние действия.}
```

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +	\item{выполнение построенного плана \textit{действия}}
```suggestion
	\item{выполнение построенного плана \textit{действия}.}
```

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +Каждое \textit{действие}, выполняемое тем или иным \textit{субъектом}, трактуется как процесс решения некоторой задачи, т.е. процесс достижения заданной \textit{цели*} в заданных условиях, и, следова
```suggestion
Каждое \textit{действие}, выполняемое тем или иным \textit{субъектом}, трактуется как процесс решения некоторой задачи, то есть процесс достижения заданной \textit{цели*} в заданных условиях, и, следовательно, выполняется целеноправленно. При этом явное указание \textit{действия} и его связи с конкретной задачей может не всегда присутствовать в памяти. Некоторые \textit{задачи} могут решаться определенными субъектами перманентно, например, оптимизация \textit{базы знаний}, поиск некорректностей и т.д. и для подобных задач не всегда есть необходимость явно вводить \textit{структуру}, являющуюся формулировкой \textit{задачи}.
```

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +Каждое \textit{действие}, выполняемое тем или иным \textit{субъектом}, трактуется как процесс решения некоторой задачи, т.е. процесс достижения заданной \textit{цели*} в заданных условиях, и, следова
И везде по тексту

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +Каждое \textit{действие}, выполняемое тем или иным \textit{субъектом}, трактуется как процесс решения некоторой задачи, т.е. процесс достижения заданной \textit{цели*} в заданных условиях, и, следова
```suggestion
Каждое \textit{действие}, выполняемое тем или иным \textit{субъектом}, трактуется как процесс решения некоторой задачи, т.е. процесс достижения заданной \textit{цели*} в заданных условиях, и, следовательно, выполняется целеноправленно. При этом явное указание \textit{действия} и его связи с конкретной задачей может не всегда присутствовать в памяти. Некоторые \textit{задачи} могут решаться определенными субъектами перманентно, например, оптимизация \textit{базы знаний}, поиск некорректностей и так далее и для подобных задач не всегда есть необходимость явно вводить \textit{структуру}, являющуюся формулировкой \textit{задачи}.
```

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +\end{scnitemize}
Всё с маленькой и через точку с запятой

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +		\scnitem{интеграция}
точно это ключевое понятие этого параграфа?

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
>  Языки представления методов в современном информационном обществе различают по их парадигмам: \textit{процедурные}, \textit{функциональные}, \textit{логические}, \textit{объектно-ориентированные} и т
я.п.м везде надо расшифровать

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
>  Как действия и задачи, методы могут быть классифицированы по различным классам. Будем называть \textbf{\textit{классом методов}} множество методов, для которых можно \underline{унифицировать} предста
Уточни, пожалуйста, в своей главе, что "программа" и "язык программирования" - это часто используемые идентификаторы "метода" и "языка представления методов"

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +В свою очередь, процедурная формулировка задачи включает в себя указание:
```suggestion
Процедурная формулировка задачи включает в себя указание:
```

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +По сути, попадание некоторого \textit{действия} во множество \textit{инициированных действий} говорит о том, что, по мнению некоторого \textit{субъекта} (заказчика, инициатора), оно готово к выполнен
```suggestion
Попадание некоторого \textit{действия} во множество \textit{инициированных действий} говорит о том, что, по мнению некоторого \textit{субъекта} (заказчика, инициатора), оно готово к выполнению и должно быть выполнено, то есть спецификация данного \textit{действия} по мнению данного \textit{субъекта} сформирована в степени, достаточной для решения поставленной \textit{задачи} и существует некоторый другой \textit{субъект} (исполнитель), который может приступать к выполнению \textit{действия}. Однако стоит отметить, что с точки зрения \textit{исполнителя} такая спецификация \textit{действия} в общем случае может оказаться недостаточной или некорректной.
```

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +По сути, попадание некоторого \textit{действия} во множество \textit{инициированных действий} говорит о том, что, по мнению некоторого \textit{субъекта} (заказчика, инициатора), оно готово к выполнен
Лучше даже не "попадение", а "принадлежность"

2023-03-31 11:30 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +Декомпозиция неатомарного действия на поддействия может иметь весьма сложный иерархический вид с большим числом уровней иерархии, т.е. поддействиями \textit{неатомарного действия} могут также \textit
Сокращения нужно убрать

2023-03-31 11:47 UTC, NikitaZotov commented
А как же научная деятельность, научный труд и творческая деятельность?

2023-03-31 12:30 UTC, KovalM commented on author/part3/chapter_actions.tex
> +		\scnitem{интеграция}
да, это вид деятельности

2023-03-31 13:59 UTC, KovalM commented on author/part3/chapter_actions.tex
>  Языки представления методов в современном информационном обществе различают по их парадигмам: \textit{процедурные}, \textit{функциональные}, \textit{логические}, \textit{объектно-ориентированные} и т
ввел я.п.м. ка часто используемый идентификатор

2023-03-31 16:54 UTC, ShunkevichDV approved these changes
Мелкие правки только

2023-03-31 16:54 UTC, ShunkevichDV commented on author/part3/chapter_actions.tex
> +\chapauthortoc{Шункевич Д.В.\\Ковалёв М.В.}
А часть про макропроцессы ТАПАЗа выкинули?

2023-03-31 16:54 UTC, ShunkevichDV commented on author/part3/chapter_actions.tex
> +Возможности решателя задач интеллектуальной системы в значительной степени определяются качеством ее базы знаний. Другими словами, при разработке решателей задач необходимо описывать не только \texti
```suggestion
Возможности решателя задач интеллектуальной системы в значительной степени определяются качеством ее базы знаний. Другими словами, при разработке решателей задач необходимо описывать не только \textit{операционную семантику} решателя, то есть семейство интерпретаторов соответствующих моделей решения задач, но и \textit{декларативную семантику} модели решения задач, то есть собственно тексты программ (не программ низкоуровневых агентов, а программ более высокого уровня, интерпретируемых соответствующим набором агентов), логические утверждения, конкретные конфигурации искусственных нейронных сетей и так далее.
```

2023-03-31 16:54 UTC, ShunkevichDV commented on author/part3/chapter_actions.tex
> +%TODO подумать, нужно ли в этом параграфе
А чего бы и нет

2023-03-31 16:54 UTC, ShunkevichDV commented on author/part3/chapter_actions.tex
> +	\item{место выполнения действия;}
Обычно пишем \item через пробел, без {

2023-03-31 16:54 UTC, ShunkevichDV commented on author/part3/chapter_actions.tex
> +			\scnitem{поведенчиское действие}
```suggestion
			\scnitem{поведенческое действие}
```

2023-03-31 16:54 UTC, ShunkevichDV commented on author/part3/chapter_actions.tex
> +			\scnitem{поведенчиское действие}
Вы чего, поведенческий аспект, поведенческая задача

2023-03-31 16:54 UTC, ShunkevichDV commented on author/part3/chapter_actions.tex
> +Термин \scnqq{метод}, таким образом, будем считать синонимичным термину \scnqq{программа} в обобщенном понимании этого термина.
Тут все правильно было, это другие кавычки. Метафора - "текст", термин или цитата - ``текст''

2023-03-31 17:08 UTC, NikitaZotov requested changes

2023-03-31 17:08 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +Отношение \textit{декларативная семантика метода*} связывает \textit{метод} и формальное описание системы понятий (фрагмент \textit{логической онтологии} соответствующей \textit{предметной области}),
Пересмотрим везде декларативную семантику метода. Должна быть денотационная

2023-03-31 17:08 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +\textit{деятельности} это целостный, целенаправленный процесс \uline{поведения} (функционирования) одного субъекта или сообщества субъектов, осуществляемый на основе хорошо или не очень хорошо продум
```suggestion
\textit{деятельность} --- это целостный, целенаправленный процесс \uline{поведения} (функционирования) одного субъекта или сообщества субъектов, осуществляемый на основе хорошо или не очень хорошо продуманной и согласованной \textit{технологии} в последнем случае качество деятельности определяется уровнем интеллекта единоличного или коллективного субъекта, осуществляющего этот целенаправленный процесс.
```

2023-03-31 17:08 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +\textit{деятельности} это целостный, целенаправленный процесс \uline{поведения} (функционирования) одного субъекта или сообщества субъектов, осуществляемый на основе хорошо или не очень хорошо продум
Это определение наверно неправильно

2023-03-31 17:08 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +		\scnitem{вид деятельности}
Хочу класс деятельности

2023-03-31 17:08 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
>  \chapter{Формализация понятий действия, задачи, метода, средства, навыка и технологии}
Здесь нет вида деятельности

2023-03-31 17:08 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +\textbf{\textit{Атомарное действие}}  выполняется одним индивидуальным субъектом и не включает в себя выполнение каких-либо дочерних действий.
```suggestion
\textbf{\textit{атомарное действие}} выполняется одним индивидуальным субъектом и не включает в себя выполнение каких-либо дочерних действий.
```

2023-03-31 17:37 UTC, KovalM commented on author/part3/chapter_actions.tex
>  	\scnsuperset{процедурная программа}
добавил непроцедурную программу

2023-03-31 17:42 UTC, KovalM commented on author/part3/chapter_actions.tex
> +\section{Спецификация методов и понятие навыка}
я бы оставил, так как навык определяется через денотационную и операционную семантику метода

2023-03-31 17:46 UTC, KovalM commented on author/part3/chapter_actions.tex
> +	\end{scnindent}
не думаю, как пример вида деятельности нормально

2023-03-31 17:49 UTC, KovalM commented on author/part3/chapter_actions.tex
> +	\scnhaselement{анализ}
в стандарте их нет, а согласовать уже не успеем

2023-03-31 17:53 UTC, KovalM commented on author/part3/chapter_actions.tex
> +					\scnitem{трудно выполнимое сложное действие}
поменял везде

2023-03-31 17:58 UTC, KovalM commented on author/part3/chapter_actions.tex
> +		\scnitem{воздействие}
добавил

2023-03-31 18:01 UTC, KovalM commented on author/part3/chapter_actions.tex
> +Отношение \textit{декларативная семантика метода*} связывает \textit{метод} и формальное описание системы понятий (фрагмент \textit{логической онтологии} соответствующей \textit{предметной области}),
поменял везде

2023-03-31 18:02 UTC, KovalM commented on author/part3/chapter_actions.tex
> +\textit{деятельности} это целостный, целенаправленный процесс \uline{поведения} (функционирования) одного субъекта или сообщества субъектов, осуществляемый на основе хорошо или не очень хорошо продум
убрал слово целенапраленный

2023-03-31 18:02 UTC, KovalM commented on author/part3/chapter_actions.tex
> +		\scnitem{вид деятельности}
Нет!

2023-03-31 18:02 UTC, KovalM commented on author/part3/chapter_actions.tex
>  \chapter{Формализация понятий действия, задачи, метода, средства, навыка и технологии}
вид будет лишним в названии, а вот деятельность добавлю

2023-03-31 18:12 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +\textit{деятельности} это целостный процесс \uline{поведения} (функционирования) одного субъекта или сообщества субъектов, осуществляемый на основе хорошо или не очень хорошо продуманной и согласован
```suggestion
\textit{деятельность} --- это целостный процесс \uline{поведения} (функционирования) одного субъекта или сообщества субъектов, осуществляемый на основе хорошо или не очень хорошо продуманной и согласованной \textit{технологии} в последнем случае качество деятельности определяется уровнем интеллекта единоличного или коллективного субъекта, осуществляющего этот целенаправленный процесс.
```

2023-03-31 18:12 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +\textit{деятельности} это целостный процесс \uline{поведения} (функционирования) одного субъекта или сообщества субъектов, осуществляемый на основе хорошо или не очень хорошо продуманной и согласован
```suggestion
\textit{деятельности} это целостный процесс \uline{поведения} (функционирования) одного субъекта или сообщества субъектов, осуществляемый на основе хорошо или не очень хорошо продуманной и согласованной \textit{технологии} в последнем случае качество деятельности определяется уровнем интеллекта единоличного или коллективного субъекта, осуществляющего этот процесс.
```

2023-04-02 19:49 UTC, KovalM commented on author/part3/chapter_actions.tex
>  Аналогичные стратегии существуют и для поиска пути решения задач, решаемых во внешней среде.
переименовал в план решения задач

2023-04-02 19:50 UTC, KovalM commented on author/part3/chapter_actions.tex
> +					\scnitem{легко выполнимое неатомарное действие}
Думаю, что да. @ShunkevichDV как считаешь, могу убрать в понятие слово неатомарное? будет просто легко выполнимое действие

2023-04-02 19:55 UTC, KovalM commented on author/part3/chapter_actions.tex
> +В частности, можно говорить о нескольких глобальных \textit{стратегиях решения информационных задач} в базах знаний. Пусть в базе знаний появился знак инициированного действия с формулировкой, соотве
Ввел

2023-04-02 21:56 UTC, NikitaZotov requested changes

2023-04-02 21:56 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +		\scnitem{стратегиях решения информационных задач}
\scnitem{стратегия решения информационных задач}

2023-04-02 21:56 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +	\scnsuperset{стратегиях решения информационных задач}
\scnitem{стратегия решения информационных задач}

2023-04-02 21:56 UTC, NikitaZotov commented on author/part3/chapter_actions.tex
> +\textit{деятельности} --- это целостный процесс \uline{поведения} (функционирования) одного субъекта или сообщества субъектов, осуществляемый на основе хорошо или не очень хорошо продуманной и соглас
\textit{деятельность}

Уже третий коммент по этому термину)

2023-04-03 01:37 UTC, NikitaZotov approved these changes

2023-04-03 10:03 UTC, merged