Bibliography 7 9
ostis-ai/monography2022 pull request #201
Opened 2023-04-01 13:58 UTC by kilativ-dotcom

2023-04-01 16:41 UTC, MksmOrlov requested changes

2023-04-01 16:41 UTC, MksmOrlov commented on author/glossary.tex
> +\end{scnreltolist}
это понятие вводится в главе 5.1, нужно ссылаться на неё. И идентификаторы согласовать

2023-04-01 16:41 UTC, MksmOrlov commented on author/glossary.tex
> +\scnheader{технология OSTIS}
С большой буквы же

2023-04-01 16:41 UTC, MksmOrlov commented on author/glossary.tex
> +\scnitem{Глава \ref{sec_security_principles}~\nameref{sec_security_principles}}
это явно ключевой знак не главы про безопасность

2023-04-01 19:38 UTC, NikitaZotov requested changes

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +\abstract{В главе рассмотрены подходы к использованию искусственного интеллекта для обеспечения безопасности традиционных информационных систем, особенности обеспечения информационной безопасности ин
Я бы не говорил "подходы к использованию искусственного интеллекта для обеспечения безопасности традиционных информационных систем"

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +\abstract{В главе рассмотрены подходы к использованию искусственного интеллекта для обеспечения безопасности традиционных информационных систем, особенности обеспечения информационной безопасности ин
Лучше "методы и средства обеспечения безопасности традиционных систем"

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +	\item безопасная разработка программного обеспечения --- искусственный интеллект может помочь создать более безопасное программное обеспечение, предоставляя разработчикам обратную связь в режиме реа
Вот это всё тоже странно выглядит с "искусственным интеллектом". Тут надо будет переформулировать как-то так, чтобы система понятий не убегала от той, что в большей части глав монографии

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +	\item безопасная разработка программного обеспечения --- искусственный интеллект может помочь создать более безопасное программное обеспечение, предоставляя разработчикам обратную связь в режиме реа
Даже если и не переформулируем, то надо выделить все понятия курсивом: "обнаружение вторжений", "Кибераналитика", "безопасная разработка программного обеспечения", "Искусственный интеллект"

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
>  При этом искусственный интеллект используется не только для защиты, но и для нападения, например для эмуляции акустических, видео и других образов с целью обмана механизмов аутентификации и дальнейше
Сокращений "т.д." и "т.к." в тексте быть не должно

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +Из монографии \scncite{Ostrouh2020} \textbf{\textit{целями обеспечения информационной безопасности традиционных интеллектуальных систем}} являются:
```suggestion
Из монографии \scncite{Ostrouh2020} \textbf{\textit{Целями обеспечения информационной безопасности традиционных интеллектуальных систем}} являются:
```

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
>  \end{figure}
Я бы убрал этот рисунок. Как мне кажется, он дублирует информацию по Экосистеме

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
>  \begin{textitemize}
Убрать этот текст

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
>  \end{textitemize}
Тоже

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +	\item принцип равнопрочности --- означает обеспечение защиты оборудования, программного обеспечения и системы управления от всех видов угроз;
Все принципы выделить курсивом и писать с большой буквы

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +Основные виды угроз в \textit{ostis-системах}:
Подчёркивания нужно заменить на курсив

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +Основные виды угроз в \textit{ostis-системах}:
Можно этот текст переделать в scn

2023-04-01 19:38 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +Мандатная политика безопасности (MAC --- mandatory access control) основывается на мандатном (принудительном) разграничении доступа, определяющемся четырьмя условиями: все субъекты и объекты системы
Может быть согласовать такие термины? Может сделать проще

2023-04-02 09:27 UTC, kilativ-dotcom commented on author/part7/chapter_security.tex
>  \end{textitemize}
начать параграф следующим абзацом, а всё до него убрать?

2023-04-02 09:27 UTC, kilativ-dotcom commented on author/part7/chapter_security.tex
> +	\item безопасная разработка программного обеспечения --- искусственный интеллект может помочь создать более безопасное программное обеспечение, предоставляя разработчикам обратную связь в режиме реа
везде в тексте выделить искусственный интеллект, где встречается?

2023-04-02 10:59 UTC, MksmOrlov approved these changes

2023-04-02 10:59 UTC, MksmOrlov commented on author/part7/chapter_security.tex
> +	\item каждое приложение, связанное с \textit{Экосистемой OSTIS}, имеет доступ к последней версии всех основных \textit{компонентов ostis-системы}, обновление компонентов выполняется автоматически;
ссылочку на **_ostis_library_section_**

2023-04-02 12:30 UTC, kilativ-dotcom commented on author/part7/chapter_security.tex
> +	\item каждое приложение, связанное с \textit{Экосистемой OSTIS}, имеет доступ к последней версии всех основных \textit{компонентов ostis-системы}, обновление компонентов выполняется автоматически;
её делать через (см. )?

2023-04-02 13:56 UTC, MksmOrlov commented on author/part7/chapter_security.tex
> +	\item каждое приложение, связанное с \textit{Экосистемой OSTIS}, имеет доступ к последней версии всех основных \textit{компонентов ostis-системы}, обновление компонентов выполняется автоматически;
да

2023-04-02 18:07 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +	\item безопасная разработка программного обеспечения --- искусственный интеллект может помочь создать более безопасное программное обеспечение, предоставляя разработчикам обратную связь в режиме реа
да

2023-04-02 18:07 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +	\item безопасная разработка программного обеспечения --- искусственный интеллект может помочь создать более безопасное программное обеспечение, предоставляя разработчикам обратную связь в режиме реа
и обрати внимание на первую букву, в некоторых местах должно быть с большой

2023-04-02 18:07 UTC, NikitaZotov commented on author/part7/chapter_security.tex
>  \end{textitemize}
Да

2023-04-02 18:23 UTC, ShunkevichDV requested changes

2023-04-02 18:23 UTC, ShunkevichDV commented on author/glossary.tex
> +\scnheader{база знаний OSTIS}
нет такого понятия, в лучше случаем база знаний ostis-системы. Если такой же термин используется и в тексте. то надо менять

2023-04-02 18:23 UTC, ShunkevichDV commented on author/glossary.tex
> +\scnitem{Глава \ref{}~\nameref{}}
Есть ощущение, что забудем, можно хотя бы на Главу 1.3 сослаться

2023-04-02 18:23 UTC, ShunkevichDV commented on author/part7/chapter_security.tex
> +\abstract{В главе рассмотрены подходы к использованию искусственного интеллекта для обеспечения безопасности традиционных информационных систем, особенности обеспечения информационной безопасности ин
Вместо ссылки на Golenkov2019 лучше сделать ссылку на главу монографии

2023-04-02 18:23 UTC, ShunkevichDV commented on author/part7/chapter_security.tex
> +\textit{Применение искусственного интеллекта в информационной безопасности}
Было правильно, курсивом мы выделяем идентификаторы сущностей, а просто для визуального выделения используется bf

2023-04-02 18:23 UTC, ShunkevichDV commented on author/part7/chapter_security.tex
> +Следует отметить, что искусственный интеллект активно применяется для мониторинга и анализа уязвимостей безопасности в сетях передачи информации (см \scncite{Isoboev2022}). Система искусственного инт
После см ставим везде точку, проверьте

2023-04-02 18:23 UTC, ShunkevichDV commented on author/part7/chapter_security.tex
> +	\item UEBA (User and Entity Behavior Analytics) --- система анализа поведения субъектов (пользователей, программ, агентов) на предмет обнаружения нестандартного поведения и использования их для обна
Было правильно, в конце пунктов списков ставим ;, так договорились

2023-04-02 18:23 UTC, ShunkevichDV commented on author/part7/chapter_security.tex
> +\textit{Применение искусственного интеллекта в информационной безопасности}
Везде проверьте

2023-04-02 18:23 UTC, ShunkevichDV commented on author/part7/chapter_security.tex
>  \end{figure}
Ну тут пытались показать именно специфику в контексте безопасности

2023-04-02 18:23 UTC, ShunkevichDV commented on author/part7/chapter_security.tex
> +\textit{Экосистема OSTIS} представляет собой коллектив взаимодействующих:
Здесь надо добавить ссылку на главу про Экосистему

2023-04-02 18:23 UTC, ShunkevichDV commented on author/part7/chapter_security.tex
>  \begin{textitemize}
Да, весь список из двух пунктов можно убрать, лучше просто сослаться на главу про Экосистему

2023-04-02 18:23 UTC, ShunkevichDV commented on biblio.bib
> +	shorthand    = {Дружинин.ред.КогниПУдВ-2002кн},
Что-то не так с shorthand

2023-04-02 18:23 UTC, ShunkevichDV commented on biblio.bib
> +	shorthand    = {Дружинин.ред.КогниПУдВ-2002кн},
Как минимум инициалы и пробел надо, даже если под редакцией

2023-04-02 18:23 UTC, ShunkevichDV commented on biblio.bib
> +@article{Golenkov2017a,
Это не совсем верно оформлено, это тезисы в сборнике конференции
Вот полная ссылка, нужно дооформить:

Семантическая модель представления и обработки баз знаний /
В. В. Голенков, Н. А. Гулякина, И. Т. Давыденко, Д. В. Шункевич // Аналитика
и управление данными в областях с интенсивным использованием данных :
сб. науч. тр. XIX Междунар. конф. DAMDID/RCDL’2017, Москва, 10–13 окт.
2017 г. / Федер. исслед. центр «Информатика и управление» Рос. акад. наук ;
под ред. Л. А. Калиниченко [и др.]. — М., 2017. — С. 412–419.

2023-04-02 18:23 UTC, ShunkevichDV commented on biblio.bib
> +@article{Golenkov2018c,
Это тоже не article, а inproceeding

Но я бы настоятельно рекомендовал сослаться на любую похожу статью в OSTIS, ITS это две странички, несерьезно

2023-04-02 18:23 UTC, ShunkevichDV commented on biblio.bib
> +	journal      = {Доклады Белорусского государственного университета информатики и радиоэлектроники},
Доклады БГУИР так и называется, не надо раскрывать

2023-04-02 20:09 UTC, kilativ-dotcom commented on biblio.bib
> +	journal      = {Доклады Белорусского государственного университета информатики и радиоэлектроники},
ссылка на эту статью заменилась ссылкой на главу монографии

2023-04-03 20:11 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +	\item с точки зрения применения \textit{искусственного интеллекта} в информационной безопасности;
Искусственный интеллект везде с большой буквы

2023-04-03 20:11 UTC, NikitaZotov commented on author/part7/chapter_security.tex
> +	\item \textit{кибераналитика} --- \textit{искусственный интеллект} также используется для анализа больших данных с целью выявления закономерностей и аномалий в системе кибербезопасности организации
Кибераналитика с большой буквы

2023-04-04 12:58 UTC, NikitaZotov approved these changes

2023-04-04 13:10 UTC, ShunkevichDV commented on author/part7/chapter_security.tex
> +	\item \textit{Принцип равнопрочности} --- означает обеспечение защиты оборудования, программного обеспечения и системы управления от всех видов угроз;
Выделять это курсивом плохо, в таком виде это не может быть идентификатором, поскольку термин получается очень общим, а в данном случае речь идет именно про аспект защиты информации. Я бы предложил заменить it на bf

2023-04-05 16:27 UTC, merged