feat: add productions models
ostis-ai/monography2022 pull request #209
Opened 2023-04-02 14:09 UTC by nastatsan

2023-04-03 08:12 UTC, MksmOrlov requested changes

2023-04-03 08:12 UTC, MksmOrlov commented on author/part3/chapter_logic_productions.tex
> +Одним из наиболее известных языков этого класса является \textbf{OPS5}. OPS5 можно рассматривать как полноценный язык программирования для продукционного программирования.
И все остальные понятия и знаки тоже повыделать

2023-04-03 08:12 UTC, MksmOrlov commented on author/part3/chapter_logic_productions.tex
> +В ряде ИС используются комбинации сетевых и продукционных моделей представления знаний. В таких моделях декларативные знания описываются в сетевом компоненте модели, а процедурные знания -- в продукц
везде посмотри, кавычки должны заканчиваться кучерявыми скобками {}

2023-04-03 08:12 UTC, MksmOrlov commented on author/part3/chapter_logic_productions.tex
> +	\item{Механизм логического вывода.}
почему тут с большой буквы?

2023-04-03 08:12 UTC, MksmOrlov commented on author/part3/chapter_logic_productions.tex
> +Факты – это одна из основных форм представления информации в системе CLIPS. Каждый факт представляет фрагмент информации, который был помещен в текущий список фактов, называемый fact-list. Факт предс
```suggestion
Факты --- это одна из основных форм представления информации в системе CLIPS. Каждый факт представляет фрагмент информации, который был помещен в текущий список фактов, называемый fact-list. Факт представляет собой основную единицу данных, используемую правилами.
```
Везде тире обозначаем как тройной дефис, проверь по тексту

2023-04-03 08:12 UTC, MksmOrlov commented on author/part3/chapter_logic_productions.tex
> +2) миварные сети: обработка информации на основе развития продукционного подхода к логическому выводу с учетом включения возможности автоматического конструирования алгоритмов для "решателей задач" и
лучше используй \begin{textitemize} \item ... \end{textitemize}

2023-04-03 08:12 UTC, MksmOrlov commented on author/part3/chapter_logic_productions.tex
не сказано, как это используется ostis-системами, хотя бы как представляется

2023-04-03 15:16 UTC, ShunkevichDV requested changes

2023-04-03 15:16 UTC, ShunkevichDV commented on author/part3/chapter_logic_productions.tex
Да, нужно какое-то введение небольшое хоть с привязкой к OSTIS

2023-04-03 15:16 UTC, ShunkevichDV commented on author/part3/chapter_logic_productions.tex
> +Миварные сети основаны на продукционном подходе "если, то…"{} с переходом к более сложной структуре правил с предусловиями, условиями, ограничениями, действиями и последействиями. Это позволяет запис
Все супер, но надо что-то сказать про то, причем тут мы вообще
Мы зачем это все рассмотрели, выводы какие

2023-04-03 15:16 UTC, ShunkevichDV commented on author/part3/chapter_logic_productions.tex
> +Продукционный язык программирования в общем случае может содержать структурные единицы различного характера. Это могут быть определения глобальных переменных, операторы управления макрогенерацией, вс
Ну тут либо продолжить как-то, либо убрать вообще Пункт. Второе хуже конечно

2023-04-09 07:42 UTC, MksmOrlov commented
А что изменилось?

2023-04-09 08:49 UTC, MksmOrlov approved these changes
С учетом комментария

2023-04-09 08:49 UTC, MksmOrlov commented on author/part3/chapter_logic_productions.tex
> +Так как в основе \textit{Технологии OSTIS} лежит \textit{многоагентный подход}, который позволяет легко интерпретировать любую информацию, то можно сделать вывод, что продукционный подход интегрирует
Так как в основе \textit{Технологии OSTIS} лежит \textit{многоагентный подход}, который позволяет легко интерпретировать любую информацию, то можно сделать вывод, что продукционный подход легко интегрируется в \textit{решатели задач} \textit{ostis-систем} в виде \textit{sc-агентов}. Интеграция \textit{Технологии OSTIS} и продукционного подхода позволяет объединить статические и динамические знания в рамках единого формализма, а также получить их графическое представление. 

Предложение "Также необходимо отметить, что в \textit{Технологии OSTIS} возможно реализовывать любые алгоритмы, так же как и в продукционный подход." не понимаю (любые ли алгоритмы в продукционном подходе можно реализовать? я не знаю) и в конце этого абзаца оно точно выглядит неуместно. Надо в начало или удалить.

2023-04-09 13:03 UTC, MksmOrlov approved these changes

2023-04-09 15:43 UTC, MksmOrlov approved these changes

2023-04-09 16:35 UTC, ShunkevichDV approved these changes

2023-04-09 16:35 UTC, merged