Fixes of Metasystem chapter
ostis-ai/monography2022 pull request #210
Opened 2023-04-02 14:58 UTC by KsenBantsevich

2023-04-02 21:59 UTC, NikitaZotov requested changes

2023-04-02 21:59 UTC, NikitaZotov commented on author/part7/chapter_ims_standard.tex
> +Следует подчеркнуть, что \textit{Стандарт OSTIS} --- это не описание некоторого состояния \textit{Технологии OSTIS}, а \uline{динамическая} информационная модель процесса эволюции этой \textit{технол
ссылку на главу 1.3

2023-04-03 15:28 UTC, ShunkevichDV approved these changes

2023-04-03 16:10 UTC, NikitaZotov approved these changes

2023-04-03 17:03 UTC, merged