Kb component design part
ostis-ai/monography2022 pull request #213
Opened 2023-04-02 16:37 UTC by KsenBantsevich

2023-04-02 19:17 UTC, MksmOrlov requested changes

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +Компонентный подход к разработке интеллектуальных компьютерных систем, реализуемый в виде \textbf{\textit{библиотеки многократно используемых компонентов ostis-систем}}, позволяет решить описанные пр
1. Ссылочку на параграф _ostis_library_section_
2. Если ты говоришь про конкретную библиотеку (Метасистемы OSTIS), то лучше используй _Библиотека многократно используемых компонентов баз знаний ostis-систем в составе Метасистемы OSTIS_. Важно, что с большой буквы и что Метасистемы. Если будет большая буква без Метасистемы, то по умолчанию это Библиотека Экосистемы OSTIS

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +	\item множество компонентов баз знаний;
```suggestion
	\item множество компонентов баз знаний и их спецификаций;
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +	\item средства поиска компонентов баз знаний на основе их спецификации.
Это библиотека не включает, об этом сказано в главе 5.1

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnheader{многократно используемый компонент баз знаний}
```suggestion
\scnheader{многократно используемый компонент базы знаний ostis-систем}
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnsuperset{семантическая окрестность понятия}
```suggestion
\scnsuperset{семантическая окрестность}
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnnote{Данный вид многократно используемых компонентов позволяет использовать только те знания, которые непосредственно необходимы для функционирования интеллектуальных систем, исключив то, что ник
```suggestion
\scnnote{Данный вид многократно используемых компонентов позволяет использовать только те знания, которые непосредственно необходимы для функционирования интеллектуальных систем, исключив то, что никак не влияет на работу конечной системы (пояснения, примеры, дидактический материал и так далее).}
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnsuperset{базы знаний прикладных систем}
```suggestion
\scnsuperset{база знаний}
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +Важнейшими компонентами, которые входят в состав библиотеки, являются \textit{онтологии предметных областей}. \textit{онтологии предметных областей}, описывающие виды знаний, которые используются в б
```suggestion
Важнейшими компонентами, которые входят в состав библиотеки, являются \textit{онтологии предметных областей}. \textit{онтологии предметных областей}, описывающие виды знаний, которые используются в большинстве интеллектуальных систем, входят в \textit{Ядро базы знаний}. \textit{Ядро базы знаний}, в свою очередь, представляет собой компонент, входящий в состав каждой базы знаний, разрабатываемой по \textit{Технологии OSTIS}, и устанавливающийся в первую очередь.
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnheader{многократно используемый компонент базы знаний}
```suggestion
\scnheader{многократно используемый компонент базы знаний ostis-систем}
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnheader{многократно используемый компонент базы знаний}
```suggestion
\scnheader{многократно используемый компонент базы знаний ostis-систем}
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnhaselement{Ядро базы знаний}
я бы сделал включение

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnexplanation{\textit{Расширенное ядро базы знаний} представляет собой расширенную версию \textit{Ядра базы знаний}.}
Понятно. А ещё лучше написать, зачем оно надо и чем отличается

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +Подробное описание представленных \textit{многократно используемых компонентов баз знаний} можно найти в \textit{Главе \ref{chapter_top_ontologies}~\nameref{chapter_top_ontologies}}, а также в \texti
```suggestion
Подробное описание представленных \textit{многократно используемых компонентов базы знаний} можно найти в \textit{Главе \ref{chapter_top_ontologies}~\nameref{chapter_top_ontologies}}, а также в \textit{Главе \ref{chapter_kb}~\nameref{chapter_kb}}.
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +Представленный список \textit{многократно используемых компонентов баз знаний} не является окончательным. В случае, когда разработчик \textit{базы знаний} интеллектуальной системы считает, что разраб
```suggestion
Представленный список \textit{многократно используемых компонентов базы знаний} не является окончательным. В случае, когда разработчик \textit{базы знаний} интеллектуальной системы считает, что разработанный им компонент сможет стать неотъемлемой частью библиотеки, то компонент будет добавлен в библиотеку, как многократно используемый, если:
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +		\item компонент не противоречит уже существующим в рамках библиотеки компонентам;
Библиотека компонентов по геометрии может содержать как компоненты по геометрии Евклида, так и по Сферической геометрии. Хоть они и противоречат, но имеют право находится даже в одной Библиотеке. Главное специфицировать, что они несовместимы

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +		\item компонент прошел верификацию и соответствует требованиям разработчиков библиотеки.
об этом сказано в 5.1. Убрать или сослаться

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +Чтобы \textit{многократно используемый компонент баз знаний} мог быть принят в библиотеку, он должен быть корректно специфицирован. Для этого используются отношения класса \textit{необходимое для уст
```suggestion
Чтобы \textit{многократно используемый компонент базы знаний} мог быть принят в библиотеку, он должен быть корректно специфицирован. Для этого используются отношения класса \textit{необходимое для установки отношение, специфицирующее многократно используемый компонент ostis-систем}. В \textit{\ref{reusable_component_section}~\nameref{reusable_component_section}} описана спецификация, общая для любых типов компонентов. Однако в зависимости от типа компонента, спецификация может расширяться. Рассмотрим \textit{необходимое для установки отношение, специфицирующее многократно используемый компонент базы знаний ostis-систем}, его поиска и установки в \textit{дочернюю ostis-систему}.
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnheader{необходимое для установки отношение, специфицирующее многократно используемый компонент баз знаний ostis-систем}
```suggestion
\scnheader{необходимое для установки отношение, специфицирующее многократно используемый компонент базы знаний ostis-систем}
```

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnhaselement{максимальный класс объектов исследования'}
Нет! Не у каждого компонента базы знаний обязан мыть максимальный класс объектов исследования. Если этот компонент -- семантическая окрестность, например?
Это отношение может быть обязательным для компонентов базы знаний, которые являются предметной областью, но не для всех же

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnhaselement{немаксимальный класс объектов исследования'}
то же самое

2023-04-02 19:17 UTC, MksmOrlov commented on author/part5/chapter_kb_design.tex
> +\scnhaselement{исследуемое отношение'}
то же самое

2023-04-03 08:24 UTC, MksmOrlov approved these changes

2023-04-03 12:54 UTC, ShunkevichDV approved these changes

2023-04-03 12:54 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Индивидульный представляет собой наполнение изолировнной части \textit{базы знаний} конкретным пользователем.
```suggestion
Индивидуальный представляет собой наполнение изолировнной части \textit{базы знаний} конкретным пользователем.
```

2023-04-03 12:54 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Процесс создания стартовой версии i можно разделить на пять основных этапа:
```suggestion
Процесс создания стартовой версии ostis-системы можно разделить на пять основных этапов:
```

2023-04-03 12:54 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Для создания файлов исходных текстов на SCg-коде может быть использован KBE (Knowledge Base source Editor)(см. \scncite{Knowledge-base-editor2022}).
```suggestion
Для создания файлов исходных текстов в SCg-коде может быть использован редактор KBE (Knowledge Base source Editor, см. \scncite{Knowledge-base-editor2022}). 
```

2023-04-03 12:54 UTC, ShunkevichDV commented on author/part5/chapter_kb_design.tex
> +Описываемая библиотека включает в себя множество компонентов баз знаний и их спецификаций.
Средства поиска стоит упомянуть, хоть они и есть в 5.1, можно просто сказать, что те же самые

2023-04-04 06:48 UTC, SHtress commented on author/part5/chapter_kb_design.tex
> +Корректно спроектированные спецификации компонентов позволят построить полную иерархию зависимостей компонентов, а также их структуру, что в свою очередь позволит беспрепятственное использование комп
Проектирование и анализ качества баз знаний являются важнейшими этапами разработки интеллектуальных компьютерных систем, так как они во многом определяют качество все интеллектуальной системы.

Для решения этих задач предложена  методология коллективной разработки базы знаний на основе Технологии OSTIS, введена Классификация и спецификация разработчиков ostis-систем, предложена модель верификации и контроля качества базы знаний, рассмотрено применение компонентного подхода при проектировании баз знаний.

Полученные результаты позволят повысить эффективность проектирования интеллектуальных систем и средств автоматизации разработки таких систем.

2023-04-04 07:20 UTC, KsenBantsevich commented on author/part5/chapter_kb_design.tex
> +Корректно спроектированные спецификации компонентов позволят построить полную иерархию зависимостей компонентов, а также их структуру, что в свою очередь позволит беспрепятственное использование комп
Немного отредактировала, но суть оставила прежнюю

2023-04-04 07:20 UTC, merged