Subject index
ostis-ai/monography2022 pull request #227
Opened 2023-04-04 14:54 UTC by grakova

2023-04-04 15:14 UTC, ShunkevichDV requested changes

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{\ref{sec_ps_scp}~\nameref{sec_ps_scp}}
Да вроде нет такого в SCP, что-то не то

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
```suggestion
	\scnitem{\ref{chapter_situation_management}~\nameref{chapter_situation_management}}
```

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
ну видимо обучающие системы

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{Глава \ref{chapter_interfaces}~\nameref{chapter_interfaces}}
Я думаю тут глава 1.1

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +\scnheader{искусственный интеллект}
Возможно с большой, надо внимательнее посмотреть

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
Глава про метасистему есть

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +\scnidtf{\textit{semantic web}}
вроде все же semantic network используется

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
Глава 1.3

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
Все эти до KQML на главу chapter_situation_management

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
Надо убрать, это не может быть ключевым знаком

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
просто OSTIS тоже

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
Глава 6.3

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +\begin{scnreltolist}{ключевой знак}
Глава 6.3

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{\nameref{chapter_ext_lang}}
Глава chapter_situation_management

2023-04-04 15:14 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
chapter_situation_management

2023-04-04 19:56 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
chapter_ims_standard

2023-04-04 19:57 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
chap_intro

2023-04-04 19:57 UTC, NikitaZotov commented on author/glossary.tex
> +\scnheader{искусственный интеллект}
да

2023-04-04 19:57 UTC, NikitaZotov commented on author/glossary.tex
> +\scnheader{искусственный интеллект}
Везде по главам надо потом пересмотреть

2023-04-04 19:57 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{Глава \ref{chapter_interfaces}~\nameref{chapter_interfaces}}
chap_intro

2023-04-04 19:58 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
chapter_learning_systems

2023-04-04 19:59 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{Глава \ref{chapter_new_generation_systems}~\nameref{chapter_new_generation_systems}}
думаю, что не надо, почти все на неё ссылаются

2023-04-04 20:10 UTC, NikitaZotov requested changes

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +\scnheader{параметр, заданный на множестве кибернетических систем}
а тут больше, там будет список длиннее. Нужно привлекать @AlexandrZagorskiy

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +\scnheader{РЗ}
почему не р.з.?

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
chapter_situation_management

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +\scnidtf{smart-общество}
```suggestion
\scnidtf{Smart-общество}
```

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
chapter_ostis_tech

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
chapter_ostis_tech

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
chapter_ostis_tech

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
chapter_ostis_tech

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
chapter_soft_platform

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +\scnheader{help-система}
как мне кажется это синоним интеллектуальной справочной системе

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +\scnheader{help-система}
нужно уточнить, потому что я не видел нигде описание этого понятия

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +\scnheader{help-система}
оно только используется, но нигде не описано)

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
chapter_ecosystem

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
chapter_ostis_tech

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +\scnheader{SC-}
интересно придумали

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
chapter_soft_platform

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
chapter_soft_platform

2023-04-04 20:10 UTC, NikitaZotov commented on author/glossary.tex
> +\scnheader{sc-JSON}
chapter_soft_platform

2023-04-05 08:50 UTC, grakova commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
исправила

2023-04-05 08:50 UTC, grakova commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
исправила

2023-04-05 08:50 UTC, grakova commented on author/glossary.tex
> +	\scnitem{\ref{sec_ps_scp}~\nameref{sec_ps_scp}}
исправила

2023-04-05 08:52 UTC, grakova commented on author/glossary.tex
> +\scnheader{искусственный интеллект}
хороший вопрос, потому что когда вместе с "в области Искусственного интеллекта", то вводила всегда с большой. но местами вроде было и с маленькой

2023-04-05 08:55 UTC, grakova commented on author/glossary.tex
> +	\scnitem{Глава \ref{}~\nameref{}}
исправила

2023-04-05 08:55 UTC, grakova commented on author/glossary.tex
> +\begin{scnreltolist}{ключевой знак}
исправила

2023-04-05 08:59 UTC, grakova commented on author/glossary.tex
> +	\scnitem{\ref{}~\nameref{}}
добавила

2023-04-05 09:02 UTC, grakova commented on author/glossary.tex
> +\scnheader{РЗ}
сложно сказать)

2023-04-06 09:53 UTC, NikitaZotov approved these changes

2023-04-06 09:55 UTC, NikitaZotov commented
Последний коммит всё затирает

2023-04-06 12:39 UTC, ShunkevichDV approved these changes

2023-04-06 12:39 UTC, ShunkevichDV commented on author/glossary.tex
> +	\scnitem{Глава \ref{chapter_interfaces}~\nameref{chapter_interfaces}}
Почему interfaces?

2023-04-06 12:43 UTC, merged