Chapter GIS
ostis-ai/monography2022 pull request #243
Opened 2023-04-06 12:49 UTC by NikitaZotov

2023-04-06 22:00 UTC, MksmOrlov requested changes
[Геоинформатика.pdf](https://github.com/ostis-ai/monography2022/files/11174670/default.pdf)

2023-04-07 21:38 UTC, ShunkevichDV approved these changes

2023-04-07 21:38 UTC, ShunkevichDV commented on author/part7/chapter_gis.tex
> +\scnheader{геонтология}
Там и ниже есть, надо поиском поискать

2023-04-08 20:41 UTC, MksmOrlov approved these changes

2023-04-09 11:28 UTC, MksmOrlov approved these changes

2023-04-09 11:28 UTC, MksmOrlov commented on author/part7/figures/berezina.png
русский язык горит, сними фокус с него

2023-04-09 11:58 UTC, merged